// Every module of the archive (archive/first-library), in the order the
// coverage, audit and benchmark tools check them. web/proof-library.mjs gives
// each a title and a browsing topic, and web/module-listing.mjs lists them
// for the browser.
export const archiveModules = [
  "w",
  "pushout",
  "fundamental_groups",
  "suspension_types",
  "field_embedding_spaces",
  "algebraic_base_change",
  "basis_generators",
  "bijective_field_embeddings",
  "embedding_counts",
  "artin_fixed_embeddings",
  "artin_hom_independence",
  "artin_finite_relations",
  "artin_loop_independence",
  "artin_evaluation",
  "artin_evaluation_matrix",
  "artin_evaluation_basis",
  "artin_fixed_evaluation",
  "artin_equivariance",
  "artin_degree",
  "artin_embedding_bound",
  "artin_classification",
  "galois_normal_bridge",
  "galois_normal_target",
  "finite_equal_dimension",
  "finite_decidable_subtypes",
  "galois_intermediate_roundtrip",
  "embedding_tower_types",
  "embedding_transport",
  "f4_formal_polynomial",
  "finite_cardinalities",
  "finite_dependent_counts",
  "finite_embedding_extensions",
  "finite_field_generators",
  "finitely_generated_algebraic",
  "generated_field_carriers",
  "normal_extensions",
  "polynomial_factor_omission",
  "polynomial_root_enumeration",
  "polynomial_splitting_leading",
  "root_generated_fields",
  "separability_base_change",
  "separable_closed_targets",
  "separable_divisors",
  "separable_polynomials",
  "simple_algebraic_extensions",
  "simple_extension_embeddings",
  "splitting_fields",

  "polynomial_monic",
  "minimal_polynomials",
  "polynomial_eval_embeddings",
  "polynomial_adjoin_universal",
  "polynomial_coordinates",
  "polynomial_residue_basis",
  "polynomial_coordinate_maps",
  "finite_algebraic_extensions",
  "polynomial_irreducible_factors",
  "polynomial_maps",
  "polynomial_extension_roots",
  "polynomial_root_existence",
  "polynomial_splitting",
  "finite_splitting_extensions",

  "field_arithmetic",
  "field_homomorphisms",
  "natural_minimum",
  "formal_series",
  "polynomial_support",
  "polynomial_ring",
  "polynomial_degree",
  "polynomial_arithmetic",
  "polynomial_division",
  "polynomial_evaluation",
  "polynomial_leading",
  "polynomial_roots",
  "polynomial_root_bound",
  "polynomial_division_unique",
  "polynomial_ideals",
  "polynomial_bezout",
  "polynomial_irreducible",
  "polynomial_remainders",
  "polynomial_residue_ring",
  "polynomial_residue_field",
  "polynomial_constants",
  "polynomial_adjoin",
  "polynomial_eval_characterization",
  "polynomial_root_evaluation",
  "polynomial_root_embeddings",
  "polynomial_cancellation",
  "polynomial_annihilator",

  "radix_uniqueness",
  "radix_equivalence",
  "radix_binary_equivalence",
  "radix_univalence_transfer",
  "binary_induction",
  "binary_equivalence",
  "binary_arithmetic_correct",
  "binary_univalence_transfer",
  "radix_induction",
  "radix_digit_laws",
  "radix_decode",
  "radix_arithmetic_correct",
  "binary_naturals",
  "binary_arithmetic",
  "radix_naturals",
  "radix_arithmetic",
  "radix_factorial",
  "structured_sets",
  "algebraic_fields",
  "field_extensions",
  "subfield_carriers",
  "field_embeddings",
  "intermediate_towers",
  "subfield_preimages",
  "subfield_images",
  "subfield_image_orders",
  "compositum_embeddings",
  "embedded_composita",
  "distinguished_extensions",
  "f4_embedded_composita",
  "field_embedding_factorization",
  "field_embedding_image",
  "f4_embedding_images",
  "galois_paths",
  "order_maps",
  "galois_orders",
  "subgroups",
  "group_operations",
  "group_homomorphisms",
  "subgroup_constructions",
  "subgroup_carriers",
  "subgroup_images",
  "group_cosets",
  "quotient_descent",
  "quotient_sets",
  "quotient_operations",
  "quotient_groups",
  "group_first_isomorphism",
  "group_hom_universes",
  "quotient_group_universal",
  "permutation_groups",
  "non_normal_subgroup",
  "vector_spaces",
  "field_vector_spaces",
  "linear_maps",
  "finite_bases",
  "linear_constructions",
  "function_linear_isos",
  "scalar_restriction",
  "coordinate_splitting",
  "coordinate_elimination",
  "finite_dimension",
  "dimension",
  "extension_degree",
  "linear_bijections",
  "finite_basis_search",
  "subspace_carriers",
  "finite_linear_lifts",
  "finite_spanning",
  "finite_family_images",
  "spanning_subfamilies",
  "scalar_extension_finiteness",
  "finite_towers",
  "linear_span",
  "finite_combinations",
  "vector_arithmetic",
  "finite_remainders",
  "finite_omission",
  "span_exchange",
  "independent_extension",
  "chain_complete_orders",
  "bourbaki_tower",
  "bourbaki_witt",
  "zorn_chain_complete",
  "vector_basis_existence",
  "vector_subspaces",
  "span_subspace",
  "predicate_chains",
  "independent_unions",
  "independent_order",
  "group_quotient_maps",
  "kernel_quotient_image",
  "normal_subgroups",
  "f4_normal_subgroups",
  "subfields",
  "subfield_generation_steps",
  "generated_subfields",
  "subfield_composita",
  "subfield_transport",
  "f4_generated_subfields",
  "subfield_intersections",
  "intermediate_fields",
  "galois_fixed_points",
  "galois_fixed_fields",
  "galois_fixing_subgroups",
  "f4_fixed_field",
  "f4_intermediate_fields",
  "f4_galois_connection",
  "decidable_subobjects",
  "f4_galois_correspondence",
  "finite_fields",
  "f4_galois",
  "f4_galois_group",
  "primes",
  "equivalences",
  "equivalence_from_inverse",
  "finite_decisions",
  "finite",
  "function_counting",
  "binomial",
  "finite_cancellation",
  "bijection_equality",
  "permutations",
  "truncation",
  "binomial_types",
  "binomial_pascal",
  "binomial_counting",
  "paths",
  "groups",
  "group_universes",
  "signed_integers",
  "suspension",
  "circle",
  "surjections",
  "maps",
  "classical",
  "schroeder_bernstein",
  "field_logic",
  "ordered_fields",
  "complete_fields",
  "dedekind_cuts",
  "field_extensionality",
  "boolean_cuts",
  "set_quotients",
  "cauchy_quotient",
  "path_actions",
  "loop_words",
  "puncture_graph",
  "bouquet_cover",
  "bouquet_generation",
  "bouquet_invariants",
  "puncture_winding",
  "bouquet_actions",
  "puncture_noncommutative",
  "field_products",
  "ring_laws",
  "complex_coordinates",
  "complex_algebra",
  "complex_polynomials",
  "polynomial_difference",
  "ordered_squares",
  "complex_norm_coordinates",
  "complex_inverses",
  "classical_complex_inverses",
  "homotopy_paths",
  "circle_degree",
  "complex_deformation",
  "integer_multiples",
  "finite_sums",
  "puncture_periods",
  "puncture_period_examples",
  "complex_periods",
  "ordered_bounds",
  "quadratic_identities",
  "complex_numbers",
  "ordered_halves",
  "field_closeness",
  "field_limits",
  "field_asymptotics",
  "cauchy_ordered",
  "complex_limits",
  "limit_periods",
  "complex_limit_periods",
  "surjective_descent",
  "descent_loop_laws",
  "homotopy_limits",
  "sample_chains",
  "sample_sum_laws",
  "contour_samples",
  "contour_sums",
  "contour_refinement",
  "contour_examples",
  "sample_error_bounds",
  "complex_contour_sums",
  "field_magnitude",
  "sample_magnitude",
  "sample_magnitude_bounds",
  "contour_error_bounds",
  "field_magnitude_close",
  "complex_magnitude",
  "contour_tag_limits",
  "field_scale_limits",
  "complex_convergence",
  "complex_contour_samples",
  "complex_contour_bounds",
  "complex_contour_tag_limits",
  "field_affine",
  "field_interval",
  "complex_affine",
  "complex_curves",
  "interval_weights",
  "sample_relations",
  "affine_variation",
  "complex_curve_variation",
  "sample_maps",
  "parameter_contours",
  "parameter_contour_bounds",
  "parameter_increment_bounds",
  "parameter_contour_limits",
  "curve_contour_limits",
  "interval_tag_bounds",
  "sample_tagged",
  "interval_sampling",
  "parameter_tag_sampling",
  "uniform_curve_tags",
  "parameter_contour_estimates",
  "curve_contour_estimates",
  "curve_tag_stability",
  "sample_refinement_tags",
  "sample_subdivisions",
  "parameter_refinement",
  "interval_refinement",
  "affine_refinement",
  "sample_subdivision_conditions",
  "complex_perturbations",
  "complex_subdivision_estimates",
  "interval_subdivisions",
  "affine_partition_refinement",
  "interval_bisection",
  "interval_midpoint_data",
  "sample_join_conditions",
  "sample_condition_maps",
  "dyadic_sampling",
  "dyadic_mesh",
  "dyadic_width_bounds",
  "dyadic_decay",
  "fine_interval_samples",
  "dyadic_tails",
  "dyadic_convergence",
  "fine_interval_tails",
  "subdivision_transport",
  "subdivision_join",
  "subdivision_join_conditions",
  "subdivision_refinement",
  "dyadic_data",
  "dyadic_refinement",
  "subdivision_tagged_zip",
  "dyadic_refinement_mesh",
  "curve_refinement_estimates",
  "dyadic_contour_estimates",
  "complex_refinement_cauchy",
  "affine_dyadic_limits",
  "affine_integrals",
  "curve_sample_sums",
  "affine_integral_midpoint",
  "affine_integral_constants",
  "field_uniform_radii",
  "complex_uniform_operations",
  "complex_scalar_continuity",
  "curve_integrand_sums",
  "affine_integral_linearity",
  "group_identity",
  "group_isomorphisms",
  "group_total_identity",
  "identity_systems",
  "group_univalence",
  "circle_group_identity",
  "cubical_paths",
  // Entry points, which no module imports.
  "basics",
  "euclid",
];

// Modules of the rebuilt library, served from library/. A name here shadows an
// archive module of the same name. The first, nat, is the natural numbers,
// which a module imports to use them.
export const libraryModules = ["nat", "classical_axioms", "universe_automorphisms", "hlevels",
  "h1_truncation", "h1_classical", "contractible_maps", "univalence", "propositions",
  "lists", "lexemes", "quotients", "algebra", "integers", "rationals"];

// The Cubist sources the test suite checks (cubist-tests/), each a module the
// workspace opens as proof.html?proof=NAME. tests/cubist-tests.test.mjs
// checks that every file is listed.
export const cubistTestModules = [
  "arguments", "implicit_parameters", "patterns", "sum_match", "glue", "face_restriction", "declared_match", "induction", "automatic_clauses",
  "automatic_clauses_groupoid", "automatic_clauses_without_hlevels", "quotient_effectiveness", "theories", "theories_without_hlevels", "theory_morphisms", "theory_sections", "theory_headers", "theory_variance", "theory_families", "theory_independent", "theory_use", "notation_views", "notation_operators", "notation_literals", "algebra_models", "integer_examples", "rational_examples", "hlevel_lemmas", "hlevel_tactic",
  "hlevel_without_import", "h1_acceptance_levels", "h1_acceptance_formers", "h1_acceptance_instances",
  "h1_acceptance_paths", "program_types", "program_types_nat_as_name", "program_types_constructor_shadowing",
  "projections", "projections_archive_helpers", "let_statements", "path_operators", "universe_generic",
  "universe_generic_bounds", "universe_generic_builtins", "universe_generic_rewriting", "inductive_values",
  "inductive_universes", "inductive_levels", "inductive_data_first", "inductive_higher",
  "inductive_rejections", "inductive_failed", "inductive_computable", "inductive_square", "inductive_beta",
  "inductive_binders", "inductive_former_values", "inductive_instance_from_position", "inductive_reduction",
  "inductive_naturals", "inductive_telescope", "inductive_imports", "inductive_shape_errors",
  "inductive_no_marker", "inductive_path_lambda", "inductive_projections", "inductive_trunc_minus_one",
  "inductive_inspection", "inductive_inspection_names", "inductive_generated_names",
  "inductive_printed_forms", "inductive_assumptions", "inductive_one_parameter_name", "computability",
  "computability_evaluation", "computability_unfolding", "induction_printed",
  "ergonomics_rewrite_obligations", "ergonomics_simp_rejections", "ergonomics_simpa_reconstruction",
  "ergonomics_type_transport_rejections", "ergonomics_simp_child_order",
  "ergonomics_simp_incompatible_candidate", "ergonomics_grouped_binder_shadowing",
  "ergonomics_grouped_universes", "ergonomics_mixed_universes", "ergonomics_generic_calc",
  "ergonomics_generic_proof_locals", "ergonomics_generic_failure", "ergonomics_repeated_match",
  "ergonomics_invalid_registry", "ergonomics_local_simp", "ergonomics_conditional_simp",
  "ergonomics_nested_premises", "ergonomics_rule_diagnostics", "ergonomics_calc_step_links",
  "ergonomics_binder_sites", "ergonomics_generic_tactic_links", "ergonomics_freeze_premise_search",
  "ergonomics_freeze_set_collision", "ergonomics_freeze_witness", "ergonomics_search_time_scope",
  "ergonomics_simp_dependent_positions", "ergonomics_rewrite_eligible_rhs", "ergonomics_generated_names",
  "ergonomics_rule_scope_rules", "ergonomics_rule_scope", "ergonomics_simp_freeze_path_identity",
  "ergonomics_simpa_freeze_path_identity", "ergonomics_simp_type_freeze_path_identity",
  "ergonomics_simpa_type_freeze_path_identity", "ergonomics_imported_failure_rules",
  "ergonomics_imported_failure", "ergonomics_simp_rules_a", "ergonomics_simp_rules_b",
  "ergonomics_simp_client_a", "ergonomics_simp_client_isolated", "ergonomics_simp_client_conflict",
  "ergonomics_simp_client_reverse_order", "ergonomics_simp_client_shadowed_rule",
  "ergonomics_multi_binder_fun", "ergonomics_tactic_sites", "ergonomics_tactic_sites_generic", "fuel_tactics",
  "fuel_residual_goals", "fuel_search_spending", "program_generic_once", "program_shadow_first",
  "program_shadow_second", "program_shadowing", "program_assumptions", "program_unfolding_hints",
  "program_unfolding_scopes", "program_optimizations", "program_generic_identity", "program_generic_caller",
  "program_unused_generic", "program_untyped_generic", "wasm_binary_literal", "wasm_bad_factorial",
  "wasm_invalid_paths", "wasm_moving_maps", "wasm_suspension_use", "driver_first_proof", "driver_sums",
  "dimension_regression", "dimension_degree_regression", "dimension_tower_regression", "dimension_invalid",
  "algebraic_extensions_invalid_embedding_claims", "algebraic_extensions_invalid_f4_root",
  "finite_spanning_finite_tower_regression", "finite_spanning_invalid_spanning",
  "finite_spanning_spanning_regression", "linear_algebra_basis_regression", "linear_algebra_chain_regression",
  "linear_algebra_general_basis_regression", "linear_algebra_invalid_basis_selection",
  "linear_algebra_invalid_linear", "linear_algebra_s3_regression",
  "polynomial_algebra_adjoined_root_regression", "polynomial_algebra_invalid_polynomial_claims",
  "polynomial_algebra_polynomial_regression", "quotient_groups_invalid_quotient",
  "quotient_groups_quotient_regression", "quotient_universal_hom_universe_regression",
  "quotient_universal_regression", "quotient_universal_bad_factorization", "h1_cauchy_quotient", "h1_zorn_step",
  "truncation_small_mere", "truncation_cauchy_same", "truncation_resize", "truncation_strict_successor",
  "truncation_rebuilt_classical", "printer_lint", "translation_failed_proofs", "translation_path_induction",
  "translation_weak_j", "mismatch_source_syntax", "mismatch_calc_naming", "source_text_messages",
  "inspection_declared_types", "inspection_shadowed_nat", "inspection_axiom_labels", "inspection_let_alias",
  "assembly_fixture", "assembly_generic_assumptions", "glue_printed", "admission_two", "reduction_demo",
  "f4_extension_loops", "f4_extension_loops_false", "fingerprint_fixture", "documentation_helper",
  "documentation_use", "declared_match_operator_call", "declarations_definitions"
];
