import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { chromium } from "playwright";
const server = spawn("python3", ["tools/serve.py", "--port", "0"], { stdio: ["ignore", "pipe", "pipe"] });
server.stderr.resume();
let browser;
try {
  const port = await new Promise((resolve, reject) => {
    let output = "";
    const timer = setTimeout(() => reject(new Error("Server did not start")), 10000);
    server.once("error", reject);
    server.stdout.on("data", data => {
      output += data;
      const match = output.match(/127\.0\.0\.1:(\d+)\//);
      if (match) { clearTimeout(timer); resolve(match[1]); }
    });
  });
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on("pageerror", error => errors.push(error.stack ?? error.message));
  await page.goto(`http://127.0.0.1:${port}/proof.html?proof=surjections&name=every_surjection_has_right_inverse`);
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled);
  await page.locator('#inspect-axioms [data-axiom="__assumption_Choice_U0"]').click();
  await page.waitForFunction(() => !document.querySelector("#kernel-specialization").hidden);
  assert.match(await page.locator("#kernel-specialization .specialization-route").textContent(), /Choice\(U\) → U := U0 → Choice\(U0\)/);
  assert.match(await page.locator("#kernel-specialization").textContent(), /not an application/);
  const opened = page.waitForEvent("popup");
  await page.locator("#open-kernel-assembly").click();
  const workbench = await opened;
  workbench.on("pageerror", error => errors.push(error.stack ?? error.message));
  await workbench.waitForFunction(() => document.querySelector("#status")?.textContent.startsWith("Cubical C checked"));
  assert.equal(await workbench.locator("#name").textContent(), "Choice(U0)");
  assert.equal(await workbench.locator("#specialization").isVisible(), true);
  assert.match(await workbench.locator("#specialization").textContent(), /axiom instance, not a proved theorem/);
  const expression = workbench.locator('[data-specialization-handle]').first();
  const handle = await expression.getAttribute("data-specialization-handle");
  await expression.click();
  assert.equal(await workbench.locator(`#assembly-node-${handle}`).getAttribute("data-opcode"), "CC_VAR");
  assert.equal(await workbench.locator(`#assembly-node-${handle}`).evaluate(node => node.classList.contains("selected")), true);
  await workbench.locator("#workbench-view").selectOption("math");
  assert.equal(await workbench.locator("#specialization").isVisible(), true);
  await workbench.locator("#specialization details").first().locator("summary").click();
  assert.match(await workbench.locator("#specialization details").first().textContent(), /U is a schema parameter/);
  assert.equal(await workbench.locator("#specialization a[href*=surjections]").count(), 1);
  await workbench.locator("#specialization a[href*=surjections]").click();
  await workbench.waitForFunction(() => document.querySelector("#inspect-name").textContent === "every_surjection_has_right_inverse" && !document.querySelector("#kernel-view").disabled);
  await page.goto(`http://127.0.0.1:${port}/proof.html?proof=groups&name=Group`);
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled);
  for (const name of ["GroupAssociativeAt", "GroupAt"]) {
    await page.locator(`#read-source .reference[data-name="${name}"]`).click();
    await page.waitForFunction(name => document.querySelector("#inspect-name").textContent === name &&
      !document.querySelector("#kernel-view").disabled, name);
    assert.equal(await page.locator("#inspect-kind").textContent(), "universe specialization");
    assert.match(await page.locator("#inspect-description").textContent(), /Inspecting.*U0/);
    assert.match(await page.locator("#view-source").getAttribute("href"), new RegExp(`proof=group_universes&name=${name}`));
  }
  await page.locator("#view-source").click();
  await page.waitForFunction(() => document.querySelector("#inspect-name").textContent === "GroupAt");
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled);
  assert.equal(await page.getByLabel("Universe U", { exact: true }).inputValue(), "0");
  await page.getByLabel("Universe U", { exact: true }).selectOption("3");
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled && document.querySelector("#inspect-type").textContent === "U4");
  assert.equal(await page.locator("#kernel-details").isVisible(), true);
  await page.locator('#read-source .reference[data-name="GroupAssociativeAt"]').first().click();
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled && document.querySelector("#inspect-name").textContent === "GroupAssociativeAt");
  assert.equal(await page.getByLabel("Universe U", { exact: true }).inputValue(), "3");
  const transferred = page.waitForEvent("popup");
  await page.locator("#open-kernel-expression").click();
  const specialized = await transferred;
  specialized.on("pageerror", error => errors.push(error.stack ?? error.message));
  await specialized.waitForFunction(() => document.querySelector("#status")?.textContent.startsWith("Cubical C checked"));
  assert.equal(await specialized.locator("#name").textContent(), "GroupAssociativeAt_U3");
  assert.doesNotMatch(await specialized.locator("#expression").textContent(), /A[0-9]|multiply[0-9]|[xyz][0-9]/);
  assert.match(await specialized.locator("#expression").textContent(), /multiply/);
  await specialized.screenshot({ path: "/tmp/template-specialization-workbench.png", fullPage: true });
  await page.locator('#read-source .reference[data-name="GroupIsoAt"]').first().click();
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled && document.querySelector("#inspect-name").textContent === "GroupIsoAt");
  const isoLine = page.locator(".source-line").filter({ hasText: "exists f : group_carrier_at" });
  await isoLine.locator('[data-name="group_carrier_at"]').first().click();
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled && document.querySelector("#inspect-name").textContent === "group_carrier_at");
  assert.equal(await page.locator("#view-source").getAttribute("href"), "#read-source");
  await page.locator("#view-source").click();
  assert.match(await page.locator(".source-line.active").textContent(), /def group_carrier_at/);
  await isoLine.locator('[data-name="G"]').click();
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled && document.querySelector("#inspect-name").textContent === "G");
  assert.match(await page.locator("#kernel-type").textContent(), /GroupAt_U3/);
  assert.match(await page.locator("#kernel-context-list").textContent(), /G/);
  assert.equal(await page.locator("#diagnostic").isVisible(), false);
  await page.goto(`http://127.0.0.1:${port}/proof.html?proof=groups&name=Group`);
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled);
  await page.locator('#read-source .reference[data-name="GroupAt"]').click();
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled && document.querySelector("#inspect-name").textContent === "GroupAt");
  await page.locator("#view-source").click();
  await page.waitForFunction(() => !document.querySelector("#kernel-view").disabled && document.querySelector("#inspect-name").textContent === "GroupAt");
  await page.locator("#back").click();
  await page.waitForFunction(() => document.querySelector("#inspect-name").textContent === "GroupAt" &&
    !document.querySelector("#kernel-view").disabled);
  assert.match(page.url(), /proof=groups/);
  assert.deepEqual(errors, []);
  console.log("PASS universe specialization: dependency link, inspector origin, workbench replay, native handles, source navigation");
} finally { await browser?.close(); server.kill(); }
