import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { chromium } from "playwright";
const server = spawn("python3", ["tools/serve.py", "--port", "0"], { stdio: ["ignore", "pipe", "pipe"] });
server.stderr.resume();
let browser;
try {
  const port = await new Promise((resolve, reject) => {
    let output = "";
    const timer = setTimeout(() => reject(new Error("Server did not start")), 10000);
    server.once("error", reject);
    server.stdout.on("data", data => {
      output += data;
      const match = output.match(/127\.0\.0\.1:(\d+)\//);
      if (match) { clearTimeout(timer); resolve(match[1]); }
    });
  });
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on("pageerror", error => errors.push(error.stack ?? error.message));
  const base = `http://127.0.0.1:${port}`;
  await page.goto(`${base}/proof.html?proof=complex_deformation&name=complex_deformation_at_one`);
  await page.waitForFunction(() => document.querySelector("#inspect-parameters-label").textContent === "Parameters and hypotheses (12)");
  assert.equal(await page.locator("#inspect-type").textContent(), "complex_linear_deformation(F, addF, mulF, one, z, error) = complex_add(F, addF, z, error)");
  assert.equal(await page.locator("#inspect-parameters").getAttribute("open"), null);
  await page.locator("#inspect-parameters summary").click();
  assert.match(await page.locator("#inspect-parameters-list").textContent(), /order : StrictOrder\(F, lt\)/);
  assert.doesNotMatch(await page.locator("#inspect-parameters-list").textContent(), /Truncate|Π/);
  await page.screenshot({ path: "/tmp/cubist-statement-desktop.png", fullPage: false });
  await page.locator('#inspect-type button[data-name="F"]').first().click();
  await page.waitForFunction(() => document.querySelector("#inspect-name").textContent === "F" && document.querySelector("#inspect-parameters").hidden);
  await page.locator("#back").click();
  await page.waitForFunction(() => !document.querySelector("#inspect-parameters").hidden);
  await page.setViewportSize({ width: 390, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.goto(`${base}/proof.html?proof=non_normal_subgroup&name=s3_point_stabilizer_not_normal`);
  await page.waitForFunction(() => document.querySelector("#inspect-type").textContent.includes("IsNormal(S3, S3PointStabilizer) -> Void"));
  assert.equal(await page.locator("#inspect-parameters").isVisible(), false);
  assert.equal(await page.locator("#diagnostic").isVisible(), false);
  await page.goto(`${base}/proof.html?proof=finite_bases&name=scalar_space_basis`);
  await page.waitForFunction(() => document.querySelector("#inspect-type").textContent === "FiniteBasis(K, ScalarSpace(K), 1)");
  assert.equal(await page.locator("#diagnostic").isVisible(), false);
  assert.equal(await page.locator("#kernel-axioms").isVisible(), false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${base}/proof.html?proof=finite_combinations&name=linear_combination_scale`);
  await page.waitForFunction(() => document.querySelector("#inspect-parameters-label").textContent === "Parameters and hypotheses (6)");
  assert.doesNotMatch(await page.locator("#inspect-type").textContent(), /b\d+|AlgebraicField|λ k/);
  assert.match(await page.locator("#inspect-type").textContent(), /linear_combination/);
  assert.doesNotMatch(await page.locator("#kernel-type").textContent(), /b\d+/);
  assert.match(await page.locator("#kernel-type").textContent(), /λ.*i/);
  await page.screenshot({ path: "/tmp/cubist-linear-scale-inspector.png" });
  assert.equal(await page.locator("#diagnostic").isVisible(), false);
  await page.goto(`${base}/proof.html?proof=vector_basis_existence&name=vector_space_has_basis`);
  await page.waitForFunction(() => document.querySelector("#inspect-type").textContent === "FieldExists(VectorBasis(K, V))");
  assert.equal(await page.locator("#inspect-parameters-label").textContent(), "Parameters and hypotheses (2)");
  assert.equal(await page.locator("#diagnostic").isVisible(), false);
  assert.match(await page.locator("#kernel-axioms").textContent(), /Choice/);
  await page.screenshot({ path: "/tmp/cubist-general-basis.png" });
  await page.goto(`${base}/proof.html?proof=vector_spaces&name=vector_scale_add_vectors`);
  await page.waitForFunction(() => document.querySelector("#inspect-name").textContent === "vector_scale_add_vectors");
  await page.screenshot({ path: "/tmp/cubist-vector-spaces-formatted.png" });
  await page.goto(`${base}/proof.html?proof=finite_dimension&name=finite_dimension_invariance`);
  await page.waitForFunction(() => document.querySelector("#inspect-type").textContent === "m = n");
  assert.equal(await page.locator("#diagnostic").isVisible(), false);
  assert.doesNotMatch(await page.locator("#kernel-axioms").textContent(), /Choice/);
  await page.goto(`${base}/proof.html?proof=extension_degree&name=tower_law`);
  await page.waitForFunction(() => document.querySelector("#inspect-name").textContent === "tower_law");
  assert.match(await page.locator("#inspect-type").textContent(), /extension_degree.*multiply_count/);
  assert.equal(await page.locator("#diagnostic").isVisible(), false);
  assert.doesNotMatch(await page.locator("#kernel-axioms").textContent(), /Choice/);
  await page.screenshot({ path: "/tmp/cubist-tower-law.png" });
  assert.deepEqual(errors, []);
  console.log("PASS source statements: conclusion, named hypotheses, binder navigation, mobile, S3, finite and general bases, dimension and tower law");
} finally { await browser?.close(); server.kill(); }
