import { writeFile } from "node:fs/promises";
import createKernel from "../../web/dist/kernel.mjs";
import { Session } from "../../web/session.mjs";
import { formatStep } from "../../web/language.mjs";
import catalogue from "../../web/proofs/catalogue.mjs";
import { euclid } from "./euclid.mjs";
import { checkPrimes } from "./check_primes.mjs";

const module = await createKernel();
const construction = euclid(module);
const { b, statement, proof } = construction;
checkPrimes(construction);
const exports = [
  "nat_add",
  "nat_mul",
  "nat_le",
  "nat_factorial",
  "Divides",
  "Prime",
  "nat_le_total",
  "bounded_least_search",
  "nontrivial_divisibility_decidable",
  "divides_transitive",
  "nontrivial_divisor_not_consecutive",
  "factorial_positive",
  "bounded_divisor_of_factorial",
  "prime_divisor_exists",
  statement,
  proof,
];
// Eliminate redundant producer instructions, then retain the exact dependency
// closure. This optimizer is untrusted: a fresh axiom-free engine replays it.
const roots = new Set(exports),
  canonical = new Map(),
  first = new Map(),
  candidates = [];
for (const step of b.k.steps) {
  const binding = b.k.bindings.get(step.name),
    key = binding.kind + ":" + binding.id;
  if (first.has(key) && !roots.has(step.name)) {
    canonical.set(step.name, first.get(key));
    continue;
  }
  canonical.set(step.name, step.name);
  if (!first.has(key)) first.set(key, step.name);
  const resolve = (x) => (x === null ? null : canonical.get(x));
  candidates.push({
    ...step,
    args: step.args.map(resolve),
    context: resolve(step.context),
    free: step.free.map(resolve),
    hidden: !roots.has(step.name),
  });
}
const byName = new Map(candidates.map((s) => [s.name, s])),
  needed = new Set();
function visit(name) {
  if (!name || needed.has(name)) return;
  needed.add(name);
  const s = byName.get(name);
  if (!s) throw new Error("Missing premise " + name);
  for (const x of [...s.args, s.context, ...s.free]) visit(x);
}
for (const root of roots) visit(root);
const steps = candidates.filter((s) => needed.has(s.name));
if (steps.some((s) => s.op === "Axiom"))
  throw new Error("Euclid proof must not use axioms");
const document = {
  format: "thth-workbench",
  version: 1,
  policy: { allowAxioms: false },
  steps,
};
console.log("Replaying", steps.length, "instructions");
const replay = new Session(module, false);
replay.import(document);
if (!replay.verify(statement, proof))
  throw new Error("Euclid replay failed verification");
const entry = {
  id: "primes",
  title: "Infinitely many primes (Euclid)",
  file: "primes.thth.json",
  source: "tools/proofs/primes.mjs",
  steps: steps.length,
  allowAxioms: false,
  exports,
  verify: [statement, proof],
  axioms: [],
};
await writeFile(
  new URL("../../web/proofs/primes.thth.json", import.meta.url),
  JSON.stringify(document, null, 2) + "\n",
);
await writeFile(
  new URL("../../web/proofs/primes.math", import.meta.url),
  "# Euclid: for every n : Nat there exists a prime p > n. No axioms.\n" +
    steps.map(formatStep).join("\n") +
    "\n",
);
await writeFile(
  new URL("../../web/proofs/primes_entry.json", import.meta.url),
  JSON.stringify(entry, null, 2) + "\n",
);
await writeFile(
  new URL("../../web/proofs/catalogue.mjs", import.meta.url),
  "// Generated by make proof-export.\nexport default " +
    JSON.stringify(
      [...catalogue.filter((p) => p.id !== entry.id), entry],
      null,
      2,
    ) +
    ";\n",
);
console.log(
  "Verified saved Euclid proof:",
  steps.length,
  "instructions; no axioms.",
  replay.engine.stats(),
);
replay.dispose();
b.k.dispose();
