// Generated by make proof-export.
export default [
  {
    "id": "u0",
    "title": "U0",
    "file": "u0.thth.json",
    "source": "src/builtins/u0.rs",
    "steps": 1,
    "allowAxioms": false,
    "exports": [
      "lib_U0"
    ]
  },
  {
    "id": "unit",
    "title": "Unit",
    "file": "unit.thth.json",
    "source": "src/builtins/unit.rs",
    "steps": 1,
    "allowAxioms": false,
    "exports": [
      "lib_Unit"
    ]
  },
  {
    "id": "singleton",
    "title": "Singleton",
    "file": "singleton.thth.json",
    "source": "src/builtins/singleton.rs",
    "steps": 1,
    "allowAxioms": false,
    "exports": [
      "lib_singleton"
    ]
  },
  {
    "id": "void",
    "title": "Void",
    "file": "void.thth.json",
    "source": "src/builtins/void.rs",
    "steps": 1,
    "allowAxioms": false,
    "exports": [
      "lib_Void"
    ]
  },
  {
    "id": "nat",
    "title": "Nat",
    "file": "nat.thth.json",
    "source": "src/builtins/nat.rs",
    "steps": 2,
    "allowAxioms": false,
    "exports": [
      "lib_Nat",
      "lib_zero"
    ]
  },
  {
    "id": "uuomega",
    "title": "Uuomega",
    "file": "uuomega.thth.json",
    "source": "src/builtins/uuomega.rs",
    "steps": 1,
    "allowAxioms": false,
    "exports": [
      "lib_Uomega"
    ]
  },
  {
    "id": "is_trunc",
    "title": "Is trunc",
    "file": "is_trunc.thth.json",
    "source": "src/builtins/is_trunc.rs",
    "steps": 16,
    "allowAxioms": false,
    "exports": [
      "lib_IsTrunc"
    ]
  },
  {
    "id": "is_set",
    "title": "Is set",
    "file": "is_set.thth.json",
    "source": "src/builtins/is_set.rs",
    "steps": 34,
    "allowAxioms": false,
    "exports": [
      "lib_IsSet"
    ]
  },
  {
    "id": "propositional_truncation",
    "title": "Propositional truncation",
    "file": "propositional_truncation.thth.json",
    "source": "src/builtins/propositional_truncation.rs",
    "steps": 49,
    "allowAxioms": true,
    "exports": [
      "lib_Trunc",
      "lib_trunc_intro",
      "lib_trunc_is_trunc",
      "lib_trunc_elim"
    ]
  },
  {
    "id": "lem",
    "title": "Law of excluded middle (LEM)",
    "file": "lem.thth.json",
    "source": "src/builtins/lem.rs",
    "steps": 63,
    "allowAxioms": true,
    "exports": [
      "LEM"
    ]
  },
  {
    "id": "aoc",
    "title": "Axiom of choice (AOC)",
    "file": "aoc.thth.json",
    "source": "src/builtins/aoc.rs",
    "steps": 111,
    "allowAxioms": true,
    "exports": [
      "AOC"
    ]
  },
  {
    "id": "pr",
    "title": "Pr",
    "file": "pr.thth.json",
    "source": "src/builtins/pr.rs",
    "steps": 44,
    "allowAxioms": false,
    "exports": [
      "lib_pr1",
      "lib_pr2"
    ]
  },
  {
    "id": "homotopy",
    "title": "Homotopy",
    "file": "homotopy.thth.json",
    "source": "src/builtins/homotopy.rs",
    "steps": 2522,
    "allowAxioms": true,
    "exports": [
      "lib_Homotopy",
      "lib_happly",
      "lib_ap",
      "lib_id",
      "lib_isEquiv",
      "lib_funext",
      "lib_funext_compute",
      "lib_funext_unique",
      "lib_id_isEquiv",
      "lib_AreEquiv",
      "lib_ua",
      "lib_transport",
      "lib_ua_elim",
      "lib_ua_unique",
      "lib_univalence"
    ]
  },
  {
    "id": "based_path_induction",
    "title": "Based path induction",
    "file": "based_path_induction.thth.json",
    "source": "src/builtins/based_path_induction.rs",
    "steps": 41,
    "allowAxioms": false,
    "exports": [
      "lib_basedPathInduction"
    ]
  },
  {
    "id": "two",
    "title": "Two",
    "file": "two.thth.json",
    "source": "src/builtins/two.rs",
    "steps": 84,
    "allowAxioms": false,
    "exports": [
      "lib_Two",
      "lib_zero2",
      "lib_one2",
      "lib_ind2",
      "lib_comp2_zero",
      "lib_comp2_one"
    ]
  },
  {
    "id": "unit_prop_unique",
    "title": "Unit prop unique",
    "file": "unit_prop_unique.thth.json",
    "source": "src/builtins/unit_prop_unique.rs",
    "steps": 10,
    "allowAxioms": false,
    "exports": [
      "lib_unit_unique"
    ]
  },
  {
    "id": "pi_void_unique",
    "title": "Pi void unique",
    "file": "pi_void_unique.thth.json",
    "source": "src/builtins/pi_void_unique.rs",
    "steps": 2570,
    "allowAxioms": true,
    "exports": [
      "lib_pi_void_unique"
    ]
  },
  {
    "id": "wnat",
    "title": "Wnat",
    "file": "wnat.thth.json",
    "source": "src/builtins/wnat.rs",
    "steps": 2665,
    "allowAxioms": true,
    "exports": [
      "lib_UNat",
      "lib_zeroU",
      "lib_succU"
    ]
  },
  {
    "id": "not",
    "title": "Not",
    "file": "not.thth.json",
    "source": "src/builtins/not.rs",
    "steps": 11,
    "allowAxioms": false,
    "exports": [
      "lib_Not"
    ]
  },
  {
    "id": "is_decidable",
    "title": "Is decidable",
    "file": "is_decidable.thth.json",
    "source": "src/builtins/is_decidable.rs",
    "steps": 23,
    "allowAxioms": false,
    "exports": [
      "lib_IsDecidable"
    ]
  },
  {
    "id": "eq_ops",
    "title": "Eq ops",
    "file": "eq_ops.thth.json",
    "source": "src/builtins/eq_ops.rs",
    "steps": 149,
    "allowAxioms": false,
    "exports": [
      "lib_EqInv",
      "lib_inv_refl",
      "lib_inv_inv",
      "lib_CatEq",
      "lib_cat_refl"
    ]
  },
  {
    "id": "create_pr1_pr2",
    "title": "Create pr1 pr2",
    "file": "create_pr1_pr2.thth.json",
    "source": "tests/no_driver/manual_library/pr.rs",
    "steps": 48,
    "allowAxioms": false,
    "exports": [
      "pr1",
      "pr2",
      "pr1_nd",
      "pr2_nd"
    ]
  },
  {
    "id": "comp",
    "title": "Function composition",
    "file": "comp.thth.json",
    "source": "tests/no_driver/comp.rs",
    "steps": 29,
    "allowAxioms": false,
    "exports": [
      "Composition",
      "composition"
    ],
    "verify": [
      "Composition",
      "composition"
    ]
  },
  {
    "id": "product_commutes",
    "title": "Product commutativity",
    "file": "product_commutes.thth.json",
    "source": "tests/no_driver/product_commutes.rs",
    "steps": 69,
    "allowAxioms": false,
    "exports": [
      "ProductCommutes",
      "product_commutes"
    ],
    "verify": [
      "ProductCommutes",
      "product_commutes"
    ]
  },
  {
    "id": "prelude_library",
    "title": "Prelude library (51 exports)",
    "file": "prelude_library.thth.json",
    "source": "src/builtins/create_builtins_vector.rs",
    "steps": 8399,
    "allowAxioms": true,
    "exports": [
      "lib_U0",
      "lib_Unit",
      "lib_singleton",
      "lib_Void",
      "lib_Nat",
      "lib_zero",
      "lib_Uomega",
      "lib_IsTrunc",
      "lib_IsSet",
      "lib_Trunc",
      "lib_trunc_intro",
      "lib_trunc_is_trunc",
      "lib_trunc_elim",
      "LEM",
      "AOC",
      "lib_pr1",
      "lib_pr2",
      "lib_Homotopy",
      "lib_happly",
      "lib_ap",
      "lib_id",
      "lib_isEquiv",
      "lib_funext",
      "lib_funext_compute",
      "lib_funext_unique",
      "lib_id_isEquiv",
      "lib_AreEquiv",
      "lib_ua",
      "lib_transport",
      "lib_ua_elim",
      "lib_ua_unique",
      "lib_univalence",
      "lib_basedPathInduction",
      "lib_Two",
      "lib_zero2",
      "lib_one2",
      "lib_ind2",
      "lib_comp2_zero",
      "lib_comp2_one",
      "lib_unit_unique",
      "lib_pi_void_unique",
      "lib_UNat",
      "lib_zeroU",
      "lib_succU",
      "lib_Not",
      "lib_IsDecidable",
      "lib_EqInv",
      "lib_inv_refl",
      "lib_inv_inv",
      "lib_CatEq",
      "lib_cat_refl"
    ]
  },
  {
    "id": "identity",
    "title": "Polymorphic identity",
    "file": "identity.thth.json",
    "source": "examples/identity.math",
    "steps": 9,
    "allowAxioms": false,
    "exports": [
      "Identity",
      "identity"
    ],
    "verify": [
      "Identity",
      "identity"
    ]
  },
  {
    "id": "wnat_equiv",
    "title": "WNat ≃ Nat (isEquiv)",
    "file": "wnat_equiv.thth.json",
    "source": "tools/proofs/wnat_equiv.mjs",
    "steps": 1910,
    "allowAxioms": true,
    "exports": [
      "wnat_to_nat",
      "nat_to_wnat",
      "wnat_roundtrip",
      "nat_roundtrip",
      "nat_roundtrip_coherent",
      "wnat_nat_coherence",
      "lib_UNat",
      "WNatToNat_isEquiv",
      "wnat_to_nat_isEquiv"
    ],
    "verify": [
      "WNatToNat_isEquiv",
      "wnat_to_nat_isEquiv"
    ],
    "axioms": [
      "function extensionality"
    ]
  },
  {
    "id": "primes",
    "title": "Infinitely many primes (Euclid)",
    "file": "primes.thth.json",
    "source": "tools/proofs/primes.mjs",
    "steps": 4329,
    "allowAxioms": false,
    "exports": [
      "nat_add",
      "nat_mul",
      "nat_le",
      "nat_factorial",
      "Divides",
      "Prime",
      "nat_le_total",
      "bounded_least_search",
      "nontrivial_divisibility_decidable",
      "divides_transitive",
      "nontrivial_divisor_not_consecutive",
      "factorial_positive",
      "bounded_divisor_of_factorial",
      "prime_divisor_exists",
      "InfinitelyManyPrimes",
      "infinitely_many_primes"
    ],
    "verify": [
      "InfinitelyManyPrimes",
      "infinitely_many_primes"
    ],
    "axioms": []
  }
];
