// Diagnostic codes. Every error and warning the checker reports has one: E
// for the parser and the elaborator, K for a refusal by the C kernel, and W
// for a warning. The errors chapter of the language reference
// (reference/errors.html) has an entry for each, at #CODE.
//
// A code names one message, written as its text with … where it varies. A
// code is never renumbered or reused. A message reworded with the same
// meaning keeps its code: edit its text here. A message that is no longer
// reported keeps its code, marked "retired". tools/diagnostic-codes.mjs gives
// new messages codes and checks that every message in the sources has one.

// The groups, by the first two characters of a code.
export const groups = {
  E1: "Reading the source",
  E2: "Files, modules and tools",
  E3: "Terms",
  E4: "Proof statements, rewriting and simplification",
  E5: "Inductive types and matching",
  E6: "Checking",
  E7: "Arguments and their inference",
  E8: "Theories and models",
  K1: "Kernel: declared types",
  K2: "Kernel: instructions",
  K3: "Kernel: terms and computation",
  W7: "Warnings",
};

export const diagnostics = [
  // Reading the source
  ["E101", "Print width must be an integer between 40 and 240."],
  ["E102", "linearizeTuples must be Boolean."],
  ["E103", "Formatting changed source tokens."],
  ["E104", "Formatting changed the expanded syntax tree."],
  ["E105", "No folded notation for …"],
  ["E106", "Unexpected character …"],
  ["E107", "Source has too many tokens."],
  ["E108", "Expected '…', found '…'."],
  ["E109", "Write := to give a value: …"],
  ["E110", "Expected a name."],
  ["E111", "… is a universe constant; pick another name."],
  ["E112", "Expected ':' or '<', found '…', as in …."],
  ["E113", "A constructor's arguments are terms; bind universes in the declaration's header."],
  ["E114", "trunc takes an integer level n ≥ -1, as in trunc(1)."],
  ["E115", "trunc(n) needs n ≥ -1: prop is trunc(-1), set is trunc(0)."],
  ["E116", "After ':' give an h-level, a universe or both, as in : prop U."],
  ["E117", "Separate names with commas: …"],
  ["E118", "Expanded tuple nesting exceeds 128."],
  ["E119", "Expression nesting exceeds 128."],
  ["E120", "A pair has only the projections .1 and .2. A tuple nests pairs to the right: the third component of (a, b, c) is .2.2."],
  ["E121", "Binary literals are limited to 256 significant bits."],
  ["E122", "Numerals are limited to 256 in this version."],
  ["E123", "Expected an expression, found '…'."],
  ["E124", "Give the motive after as: match v as z return T { … }."],
  ["E125", "Expected '}' to close the match."],
  ["E126", "Separate binder groups with commas: fun (a : A, b : B) => …"],
  ["E127", "Only forall and fun bind a universe variable: exists has no level form."],
  ["E128", "End …'s type with a dot: … n : Nat. P(n)"],
  ["E129", "Write a space after the . that ends …'s type: … n : Nat. P(n)"],
  ["E130", "Pattern nesting exceeds 128."],
  ["E131", "A pair pattern needs at least two components."],
  ["E132", "obligations by supports hlevel (with optional hints), rfl, a proof block, or a whole clause term; put simp or simpa inside a proof block."],
  ["E133", "Expected '}' to close obligations."],
  ["E134", "Block nesting exceeds 128."],
  ["E135", "Separate names with commas: intro m, n;"],
  ["E136", "have was removed: write let name : T := term; or prove the claim in a block, let name : T { … }."],
  ["E137", "show was removed: prove the restated goal in a block, let h : T { … }, then exact h;."],
  ["E138", "suffices was removed: prove the claim first, let h : T { … }, then prove the goal from h."],
  ["E139", "Expected a proof statement; found '…'."],
  ["E140", "Use obtain to unpack a pair."],
  ["E141", "rw requires a path."],
  ["E142", "rw target must be lhs or rhs."],
  ["E143", "rw occurrence must be a positive integer."],
  ["E144", "simp only requires an explicit rule list."],
  ["E145", "simp only cannot exclude rules."],
  ["E146", "The … statement takes apart one value; … the first, then the next inside each clause.", "retired"],
  ["E147", "The … statement takes its motive from the goal: write … v { c(xs) => { … } … } without as or return."],
  ["E148", "A clause of the … statement is a proof block: c(xs) => { … }."],
  ["E149", "simp_rule priority must be an integer from 0 to 1000."],
  ["E150", "Expected '}' to close the inductive declaration."],
  ["E151", "Imports must come before declarations."],
  ["E152", "Expected a declaration or directive: def, computable def, inductive, evaluate, print, simp_rule, simp_set or theory."],
  ["E153", "Write := to give a value: def name : T := term; here `=` read as an equality type"],
  ["E154", "Cannot locate a right-hand pair's enclosing parentheses."],
  ["E155", "Tuple linearization changed the expanded syntax tree."],
  ["E156", "Give the motive after as: induction v as z return T { … }."],
  ["E157", "Expected '}' to close the induction."],
  ["E158", "Expected '}' to close the …."],
  ["E159", "print shows evaluate(term), typeof(term) or inspect(term)."],
  ["E162", "A match on several values takes its motive from return T or the type expected of it, without as."],
  ["E163", "The induction statement takes apart one value; take the first, then the next inside each clause."],
  ["E164", "cases was removed: write match value { left(a) => { … } right(b) => { … } }."],
  ["E165", "Close double braces with }}, two braces together."],
  ["E166", "Implicit parameters are in double braces: def f{{U < UU0, A : U}}(…)."],
  ["E167", "A notation is a binary operator: x + y, x * y, x < y or x <= y."],
  ["E168", "Expected '}' to close the theory."],
  ["E169", "A sort is a set or a proposition: sort M : set; or sort P : prop;"],
  ["E170", "Expected ':' and the type of …, as in …"],
  ["E175", "… is reserved, as a keyword or a built-in type of the language; pick another name."],
  // Files, modules and tools
  ["E201", "Could not load …: HTTP …"],
  ["E202", "The declaration limit must be a positive number of milliseconds."],
  ["E203", "No benchmark report yet. Run npm run benchmark:cubical."],
  ["E204", "Syntax display limit"],
  ["E205", "Expected a level, not …."],
  ["E206", "Unsupported cubical notation: …"],
  ["E207", "The representation option was removed with the differential fixtures: Nat, W and pushouts are source declarations."],
  ["E208", "H1 is no longer experimental: declared types are on by default, so drop the experimental option."],
  ["E209", "Cyclic source import: …"],
  ["E210", "Source was not discovered: …"],
  ["E211", "No checked native definition for this name."],
  ["E212", "Unsupported cubical transfer format."],
  ["E213", "Missing source module …."],
  ["E214", "Native source is not available at …."],
  ["E215", "Check a proof first."],
  ["E216", "Unsupported cubical command."],
  ["E217", "Unknown mathematical display node: …"],
  ["E218", "Unknown module place: …."],
  ["E219", "Invalid module name: …."],
  ["E220", "No module named … in ……."],
  ["E221", "Unable to load source: "],
  ["E222", "The checking worker stopped making progress. Reload the page to restart the kernel."],
  ["E223", "Recheck the current source before replacing this simplification."],
  ["E224", "Allow a new tab to open the kernel workbench."],
  ["E225", "Source exceeds 1 MB."],
  ["E226", "Unable to load the checking worker."],
  ["E227", "Unable to load the checking worker. Build with make wasm."],
  ["E228", "This expression transfer is no longer available. Open it again from the proof inspector."],
  ["E229", "check requires a module or .cubist file."],
  ["E230", "Check a source first."],
  ["E231", "Ambiguous name; use a qualified binding: …"],
  ["E232", "Inspect a checked name first."],
  ["E233", "Expected expression or type."],
  ["E234", "export requires a filename."],
  ["E235", "Unknown command …. Type help."],
  ["E236", "… is a command of the console, not of an entry."],
  ["E237", "Unknown command …. /help lists the commands."],
  ["E238", "This session cannot list its modules."],
  ["E239", "Module … was not loaded."],
  ["E240", "… did not check."],
  ["E241", "Could not load the file index: HTTP …"],
  ["E242", "The prelude option was removed: no module is imported automatically, so a module imports nat itself; bundledNat controls nat's bundled source."],
  // Terms
  ["E301", "Expected cubical syntax."],
  ["E302", "Expected a dimension binder."],
  ["E303", "Cubical prototype supports 64 simultaneously live dimensions."],
  ["E304", "Internal elaboration error: … is already bound."],
  ["E305", "At most 64 simultaneous cubical dimensions are supported."],
  ["E306", "Unglue extension requires an explicit Glue type.", "retired"],
  ["E307", "Unglue equivalence requires an explicit Glue type.", "retired"],
  ["E308", "Cubical lattice term-size budget exceeded."],
  ["E309", "Expected a lattice DNF."],
  ["E310", "Malformed lattice generator."],
  ["E311", "Invalid dimension name."],
  ["E312", "Expected endpoint 0 or 1."],
  ["E313", "Supply the checked generic native-equivalence round-trip lemma."],
  ["E314", "Supply the checked generic native univalence inverse laws.", "retired"],
  ["E315", "Cubical syntax construction term-size budget exceeded."],
  ["E316", "Simplification term-size budget exceeded."],
  ["E317", "Malformed universe constant: …."],
  ["E318", "A translator needs a checker: the elaborator over a kernel."],
  ["E319", "Expected an interval coordinate: 0, 1, a coordinate name, -i, i & j or i | j (or flip, meet, join)."],
  ["E320", "Expected a face formula: on(i, 0 or 1), and/or, 0 or 1."],
  ["E321", "A universe variable's bound must be UU0, as in U < UU0."],
  ["E322", "Expected a universe: U0, UU0, a universe variable, next(E) or max(E, F)."],
  ["E323", "Expected fun (i : Interval) => ... in a cubical binder."],
  ["E324", "The evaluated term"],
  ["E325", "The evaluated term has type …, but the expected value has type …."],
  ["E326", "The term evaluates to …, not …."],
  ["E327", "Simplification rule … is already registered in this module."],
  ["E328", "Simplification set … is already declared in this module."],
  ["E329", "Native cubical check rejected: …"],
  ["E330", "This computable declaration"],
  ["E331", "Simplification premise witness must be local: …."],
  ["E332", "sym requires a path."],
  ["E333", "p ++ q concatenates paths; found no path."],
  ["E334", "trans requires paths."],
  ["E335", "Numerals and induction require an imported Nat with zero and succ constructors."],
  ["E336", "Missing source expression."],
  ["E337", "No checked definition to unfold: …"],
  ["E338", "path i => ... needs an expected Path or PathP type."],
  ["E339", "along requires a homogeneous base path."],
  ["E340", "Untranslated dependency: …"],
  ["E341", "Interval coordinates can only be used in interval arguments."],
  ["E342", "Universe was removed: bind a universe variable as U < UU0."],
  ["E343", "Untranslated name: …"],
  ["E344", "Too many lambda binders for the expected type."],
  ["E345", "A universe lambda needs a universe-generic type: forall U < UU0. …"],
  ["E346", "Untyped lambda requires an expected function type."],
  ["E347", "… combines interval coordinates, as in p @ i … j; it is not an operation on terms."],
  ["E348", "Untranslated operator: …"],
  ["E349", "Projection .… requires a dependent pair; found a value of type …."],
  ["E350", "Pair requires an expected type."],
  ["E351", "Expected a Sigma type for pair."],
  ["E352", "Source application is not a function."],
  ["E353", "match requires a value of a declared type, or of a sum."],
  ["E354", "match requires a sum type."],
  ["E355", "A match on a sum has a return type and the clauses left x => …; right y => …."],
  ["E356", "unpack requires a dependent pair."],
  ["E357", "Untranslated syntax: …"],
  ["E358", "Proof block has no conclusion."],
  ["E359", "Proof tactic not yet translated: …"],
  ["E360", "rw requires a homogeneous equality goal."],
  ["E361", "hlevel uses the library module hlevels: add import hlevels;"],
  ["E362", "hlevel does not use quantified hints yet: apply … to its arguments."],
  ["E363", "The hint … has type …, which states no h-level."],
  ["E364", "hlevel proves IsContr, IsProp, IsSet or HasLevel, or an equality in a proposition; the goal is …."],
  ["E365", "hlevel needs the type of the equality's sides to be in a universe."],
  ["E366", "hlevel could not prove ……; …."],
  ["E367", "Simplification cycle detected in the selected rules. … returned the goal to where it was … rewrite… earlier."],
  ["E368", "General simplification requires a type-valued goal."],
  ["E369", "Simplification rewrite budget exceeded."],
  ["E370", "simp only requires a homogeneous equality goal."],
  ["E371", "induction requires a value of a declared type."],
  ["E372", "… stands for a universe that the printer could not show: write the universe in its place, such as U0 or a universe variable."],
  ["E373", "-p reverses a path; found no path."],
  ["E374", "… has no named parameters: a named argument gives a parameter that a definition declares."],
  ["E375", "… has no parameter …; its parameters are …."],
  ["E376", "… has two parameters named …: give them by position.", "retired"],
  ["E377", "The argument … is given twice."],
  ["E378", "… takes its arguments explicitly: a hole _ or a named argument is an argument of a definition or a function."],
  ["E379", "… is a declared type or a constructor, whose arguments are written out: a hole _ or a named argument is an argument of a definition or a function."],
  ["E380", "A recursive call of … takes its arguments explicitly."],
  ["E381", "Give the universe … of … explicitly: a universe argument is not inferred.", "retired"],
  ["E382", "… takes … argument…; this is one more."],
  ["E383", "The hole for … of … was solved as …, which does not have its type …."],
  ["E385", "A hole _ stands for an argument of a call, which the call's other arguments or the type expected of it determine; anywhere else, write the term."],
  ["E386", "The argument … of … needs the type of its …, …, which mentions a hole nothing determines…. Give the hole explicitly."],
  ["E387", "The … of … is not determined: … fits, and so would a larger universe…. Give it explicitly.", "retired"],
  ["E388", "Nothing determines the … of …, of type …: not the other arguments' types, nor the type expected of the call…. Give it explicitly."],
  ["E389", "The … of … would be …, which mentions a variable bound inside an argument, out of its scope…. Give it explicitly."],
  ["E390", "The universe … of … would be …, which is not below UU0. Give it explicitly."],
  ["E391", "Nothing determines the universe … of …: no argument's type bounds it, and the call's type depends on it. Give it explicitly."],
  ["E392", "The … of … is not determined: … fits, and so would … universe…. Give it explicitly."],
  ["E393", "… takes … argument… by position; give its implicit parameters … in double braces, in order or by name, as …{{…}}(…) or …{{… := …}}(…)."],
  ["E394", "… is a theory: its models are ….Model(U), built with ….make(…)."],
  // Proof statements, rewriting and simplification
  ["E401", "Univalence requires a universe."],
  ["E402", "… takes a universe below UU0."],
  ["E403", "Too many arguments to …."],
  ["E404", "… needs a universe argument."],
  ["E405", "… with a truncation former needs a universe argument."],
  ["E406", "Logical assumptions require a universe and an explicit native context."],
  ["E407", "… holds only for universes below UU0."],
  ["E408", "Invalid arguments to …."],
  ["E409", "A composition wall has syntax face(i, 0 or 1, fun (j : Interval) => ...)."],
  ["E410", "A composition face needs an outer interval coordinate and endpoint 0 or 1."],
  ["E411", "pair_induction requires a dependent pair."],
  ["E412", "FunExt needs a universe."],
  ["E413", "FunExt takes a universe below UU0."],
  ["E414", "absurd requires an expected type."],
  ["E415", "Sum injection requires an expected type."],
  ["E416", "Expected a sum type."],
  ["E417", "cong requires a path."],
  ["E418", "Dependent action needs a function and a path with the supplied endpoints."],
  ["E419", "apd_path needs a dependent function and a homogeneous path."],
  ["E420", "transport requires a path."],
  ["E421", "Transport endpoints do not match."],
  ["E422", "Path induction endpoints/carrier do not match."],
  ["E423", "Based induction needs universes."],
  ["E424", "A scrutinee depends on a hypothesis about another scrutinee; eliminate that hypothesis too."],
  ["E425", "Internal elaboration error: a motive instance needs one value per scrutinee."],
  ["E426", "Internal elaboration error: unknown plan step …."],
  ["E427", "Internal elaboration error: a … step has no forward direction."],
  ["E428", "Expected homogeneous equality paths for composition."],
  ["E429", "Path endpoints do not match."],
  ["E430", "A general goal rewrite requires a checked path of types."],
  ["E431", "rw requires a homogeneous equality proof."],
  ["E432", "Simplification rule has too many parameters."],
  ["E433", "simp only requires homogeneous equality lemmas."],
  ["E434", "A universe-generic rule is matched only where its universe is a bare variable; supply its universe argument, as in lemma(U0)."],
  ["E435", "A universe-generic rule's universe is not determined by the matched side; supply it, as in lemma(U0)."],
  ["E436", "A simplification rule parameter is not determined by the matched side; supply arguments."],
  ["E437", "Simplification rule lost a parameter."],
  ["E438", "Invalid rewrite occurrence."],
  ["E439", "Rewrite traversal budget exceeded."],
  ["E440", "Rewrite candidate budget exceeded."],
  ["E441", "Rewrite match occurs in an unsupported dependent position."],
  ["E442", "Rewrite occurrence … was not found (… eligible matches)."],
  ["E443", "Simplification set … is ambiguous: …."],
  ["E444", "Statements after exact are unreachable."],
  ["E445", "Statements after rfl are unreachable."],
  ["E446", "rfl requires a homogeneous equality goal."],
  ["E447", "Statements after calc are unreachable."],
  ["E448", "calc requires a homogeneous equality goal."],
  ["E449", "calc requires at least one step."],
  ["E450", "calc step left endpoint does not match the preceding endpoint. The step starts at …; the chain so far ends at …."],
  ["E451", "calc final endpoint does not match the goal. The chain ends at …; the goal's right side is …."],
  ["E452", "rw left an unresolved equality goal; add a following proof statement.…"],
  ["E453", "A simplified hypothesis copy must be followed by a proof statement."],
  ["E454", "simp at requires a local hypothesis: …."],
  ["E455", "simp left a type goal; add a following proof statement.…"],
  ["E456", "simp only left an unresolved equality goal; add a following proof statement.……"],
  ["E457", "Statements after simpa are unreachable."],
  ["E458", "intro requires a dependent function goal."],
  ["E459", "Statements after hlevel are unreachable."],
  ["E460", "ext requires equality of functions with a fixed type."],
  ["E461", "ext requires equality of functions."],
  ["E462", "Statements after over are unreachable."],
  ["E463", "over requires an expected PathP goal."],
  ["E464", "over requires a homogeneous base path."],
  ["E465", "let states a type after the colon; found a value of type …."],
  ["E466", "obtain requires a dependent pair matching its pattern."],
  ["E467", "Statements after … are unreachable: each clause's block closes the goal."],
  ["E468", "Statements after cases are not yet translated.", "retired"],
  ["E469", "cases requires a sum type.", "retired"],
  ["E470", "glue needs the Glue type it builds an element of: write typed(Glue(…), glue(…))."],
  ["E471", "glue builds an element of a Glue type."],
  ["E472", "unglue takes an element of a Glue type."],
  ["E473", "A face needs an interval coordinate and endpoint 0 or 1."],
  ["E474", "A Glue piece has syntax face(i, 0 or 1, T, e) or face_when(φ, T, e)."],
  ["E475", "A glue value has syntax face(i, 0 or 1, t) or face_when(φ, t)."],
  ["E476", "open takes a model of a theory, such as m : Group.Model(U0); this is a value of type …."],
  // Inductive types and matching
  ["E501", "trunc(n) is supported up to n = …."],
  ["E502", "A sort is type, set, prop or trunc(n) for an integer n ≥ -1."],
  ["E503", "The declared type … already exists."],
  ["E504", "A signature has too many parameters."],
  ["E505", "The path's fiber must live in a universe."],
  ["E506", "Declared types need the instruction kernel."],
  ["E507", "… uses the assumption …: a declared type's parameters and constructors cannot use assumptions, since its signature is closed."],
  ["E508", "A universe parameter cannot be named …: in a declaration's result position that word is an h-level."],
  ["E509", "… is already a constructor of …."],
  ["E510", "A constructor cannot be named …, as its type is."],
  ["E511", "… occurs in a negative position: …'s argument … takes an argument that mentions … or another argument of …."],
  ["E512", "…'s argument … mentions … but is not one: in H1 an argument is … itself, a function into it, or a path in it."],
  ["E513", "The type of … is not a type."],
  ["E514", "…'s argument … lives in a universe above …'s declared one: a declared type cannot lower its data (K2.5)."],
  ["E515", "Inside its declaration, … is applied to its own parameters, …(…): another argument would be an index, which H1 does not admit."],
  ["E516", "… takes no arguments."],
  ["E517", "… takes … argument…: …(…)."],
  ["E518", "A universe argument must lie below UU0: U0, U1, … or a universe variable."],
  ["E519", "… needs an expected type, to know which …(…) it builds: "],
  ["E520", "apply it at a point where …(…) is expected, as in typed(…(…), …… @ i)."],
  ["E521", "write typed(…(…), ……)."],
  ["E522", "… builds …(…), but … is expected here."],
  ["E523", "Apply … to its … arguments: the kernel takes its data before its positions."],
  ["E524", "… takes … argument…; apply a path constructor at a coordinate with @."],
  ["E525", "Apply … to all its … arguments: the kernel takes its data before its positions."],
  ["E526", "… takes fewer arguments."],
  ["E527", "The declared type of the matched value is not in scope."],
  ["E528", "… has no constructor …: its constructors are …."],
  ["E529", "… has two clauses."],
  ["E530", "… is a point constructor: give its computational clause in …, before obligations."],
  ["E531", "… on … needs a clause for …. Give path clauses in obligations { … }, or obligations by { … }."],
  ["E532", "obligations by a term or proof block needs exactly one missing declared path clause; found …. Use named obligations { … } for separate clauses."],
  ["E533", "The motive mentions … itself: write it over the matched value, match … as z return … z …, so that recursive calls have their own types."],
  ["E534", "… needs its result's type: give return T, or use it where its type is known."],
  ["E535", "The … statement takes apart a value of a declared type; for a sum, use cases.", "retired"],
  ["E536", "The … statement takes apart a value of a declared type."],
  ["E537", "The … statement takes apart a value of a declared type, and declared types (H1) are switched off in this kernel session."],
  ["E538", "… takes … argument… here: …(…) with … names."],
  ["E539", "Write the dimension… of … after @, as the point the clause covers: …."],
  ["E540", "… has no dimensions to name."],
  ["E541", "… is a path constructor: name its … dimension… after its arguments, as in …."],
  ["E542", "The clause type of … has fewer arguments than expected."],
  ["E543", "The clause type of … has fewer dimensions than expected."],
  ["E544", "Cannot generate …: import hlevels and supply h-level evidence for the motive, or give the clause explicitly."],
  ["E545", "The obligation … is not a path clause."],
  ["E546", "Cannot generate …: … must be …; …. Give checked h-level evidence, or an explicit obligation."],
  ["E547", "… is being defined: it can call itself only on an argument of a constructor that its match takes apart, as …(m) in succ(m) => …, when that match on one of its parameters is its whole body."],
  ["E548", "… takes … argument…."],
  ["E549", "A recursive call of … changes …: the match needs its motive over its other parameters."],
  ["E550", "A recursive call of … passes … unchanged: the type of the matched … depends on it."],
  ["E551", "A recursive call of … passes the universe parameter … unchanged."],
  ["E552", "The recursive call of … is not on an argument of the matched constructor: only structural recursion, …."],
  ["E553", "… takes … argument… here, as an argument of the matched constructor."],
  ["E554", "… is a …-dimensional path of the matched type, not an element: call … on it at its dimensions, as …(……)."],
  ["E555", "… is an element of the matched type, not a path: call …(…) without @."],
  ["E556", "Internal elaboration error: the recursive result of … takes fewer hypotheses."],
  ["E557", "… takes … argument… here, then … if you name them: …(…) with … or … names."],
  ["E558", "This clause has … pattern…; the match takes apart … value…."],
  ["E559", "This clause is never reached: the clauses before it take every case it would."],
  ["E560", "… is not of a declared type: its patterns are variables or _."],
  ["E561", "The match has no case for …… in …."],
  ["E562", "… is a path constructor: name its … dimension… after its arguments."],
  ["E563", "The induction statement takes apart a value of a declared type; for a sum, use match."],
  ["E564", "The … statement takes apart a value of a declared type, or of a sum."],
  ["E565", "A sum's clauses are left(a) => { … } and right(b) => { … }; found …."],
  ["E566", "A sum's clause names its side's value: …(a) => { … }."],
  ["E567", "The match on a sum needs a clause for …: …(a) => { … }."],
  ["E568", "… has two parameters named …: give each its own name."],
  ["E569", "… has two arguments named …: give each its own name."],
  ["E570", "… is bound twice in this clause: name each variable once."],
  // Checking
  ["E601", "Unsupported library assumption: …"],
  ["E602", "Only LEM and Choice have rebuilt truncation signatures."],
  ["E603", "Rebuilt LEM and Choice require an admitted proposition truncation."],
  ["E604", "Instruction kernel: …"],
  ["E605", "An assumption needs a checked type."],
  ["E606", "Type mismatch: found …, expected …."],
  ["E607", "Invalid cubical dimension binding."],
  ["E608", "Cubical dimension indices must be distinct."],
  ["E609", "… is not in instruction mode yet."],
  ["E610", "Unbound variable …."],
  ["E611", "Composition tube disagrees with its base."],
  ["E612", "A Glue value's image disagrees with the base."],
  ["E613", "A constructor names an instance of a declared type."],
  ["E614", "The eliminator's motive is over another declared type."],
  ["E615", "A signature's former binds its universe parameters first."],
  ["E616", "A signature's former binds its parameters after its levels."],
  ["E617", "Could not allocate a symbol."],
  ["E618", "An instance takes each of its signature's parameters."],
  ["E619", "An instance gives each recorded universe parameter its level, and no other."],
  ["E620", "An erased universe parameter has no parameter to read it from."],
  ["E621", "Two pieces disagree where their faces meet."],
  ["E622", "No interval dimension is free for a binder."],
  ["E623", "The motive is a family over another type."],
  ["E624", "Expected …, found …."],
  ["E625", "Type mismatch."],
  ["E626", "The policy … ranked a move that is not open."],
  ["E627", "Unknown move …."],
  ["E628", "Invalid position."],
  ["E629", "Declaration time limit exceeded."],
  ["E630", "Unknown judgement …."],
  ["E631", "Unknown context entry …."],
  ["E632", "The cubical kernel module encodes syntax as ABI version …, but this code expects version …. Rebuild it with `make wasm`."],
  ["E633", "Could not allocate cubical kernel session."],
  ["E634", "Cubical kernel session is disposed."],
  ["E635", "This cubical kernel module has no work counters. Rebuild it with `make wasm`."],
  ["E636", "Unsupported cubical constructor: …"],
  ["E637", "Cubical nodes have at most four children."],
  ["E638", "Normalize a term or type an instruction derived."],
  ["E639", "Unknown checked cubical definition."],
  ["E640", "Unknown cubical node handle."],
  ["E641", "Display simplification budget"],
  ["E642", "Invalid reduction location."],
  ["E643", "This location does not support the selected reduction."],
  ["E644", "Unknown reduction operation."],
  ["E645", "Unknown reduction target."],
  ["E646", "No checked definition for …."],
  ["E647", "Invalid dimension literal."],
  ["E648", "Unbound cubical dimension: …"],
  ["E649", "Unknown checked cubical definition: …"],
  ["E650", "A constructor needs its number."],
  ["E651", "Unsupported cubical syntax: …"],
  ["E652", "Unknown declared type: …"],
  ["E653", "Invalid universe level: …"],
  ["E654", "Invalid universe level constant."],
  ["E655", "Expected a universe level."],
  ["E656", "Expected a universe level, not …."],
  ["E657", "Invalid transport face descriptor."],
  ["E658", "Invalid cubical tube list."],
  ["E659", "Invalid cubical Glue system."],
  ["E660", "Invalid cubical Glue element system."],
  ["E661", "Unsupported cubical node: …"],
  ["E662", "Declaration transaction was already finished."],
  ["E663", "A path is applied at an interval point; found a face formula."],
  ["E664", "A transport's face is a face formula; found an interval point."],
  ["E665", "A partial element's face is a face formula; found an interval point."],
  // Arguments and their inference
  ["E701", "… has no implicit parameters: give its arguments in parentheses, as …(…)."],
  ["E702", "… has … implicit parameter…, …; the double braces give …."],
  ["E703", "A recursive call of … passes its implicit parameters unchanged: give only the others, as …(…)."],
  ["E704", "… is not an implicit parameter of …: give it in parentheses, as …(… := …)."],
  ["E705", "… is an implicit parameter of …: give it in double braces, as …{{… := …}}(…)."],
  // Theories and models
  ["E801", "Renaming … to … would capture a variable named …; pick another name."],
  ["E802", "… gets a field named … from both … and …: rename one, as in …(… := …)."],
  ["E803", "… has two fields named …: give each its own name."],
  ["E804", "… would stand for both … and … in …: a notation means one operation; rename one's notation."],
  ["E805", "… is not a theory here: … extends theories in scope."],
  ["E806", "… has two parents labelled …: label one, as in other : …."],
  ["E807", "… has no field …; its fields are …."],
  ["E808", "… is renamed twice."],
  ["E809", "A notation names an operation's two arguments; … is not an operation of two."],
  ["E810", "A notation names an operation's two arguments, as in mul(x, y : M) : M notation x * y; … has …."],
  ["E811", "The notation of … writes its arguments in order: … … …."],
  ["E812", "A field's name is a plain name; … is not."],
  ["E813", "… has no fields: a theory declares sorts, operations and laws."],
  ["E814", "The sorts of … need …, from hlevels: import hlevels;"],
  ["E815", "… is a model of …, which has no field …: it has ……."],
  ["E816", "This is a model of …, which has no field …: it has ……."],
  ["E817", "…'s models have no homomorphisms: …."],
  ["E818", "The law … must state a proposition: an equation between elements of a sort, Void, or forall, -> or and over those; …. A law holds no data, and homomorphisms ignore laws: declare data as an operation or a constant."],
  // Kernel: declared types
  ["K101", "Dimension renaming allocation failed."],
  ["K102", "A boundary is nested too deeply."],
  ["K103", "A boundary applies a constructor to too many arguments."],
  ["K104", "A boundary applies an earlier constructor to all its arguments."],
  ["K105", "A boundary is not a constructor expression."],
  ["K106", "A cube is nested too deeply."],
  ["K107", "A cube is the sort or a path type over it."],
  ["K108", "The signature has no such constructor."],
  ["K109", "A constructor's type has fewer arguments than it takes."],
  ["K110", "A position's displayed cube does not follow its cube."],
  ["K111", "Unknown judgement."],
  ["K112", "Expected an eliminator in progress."],
  ["K113", "An eliminator's motive is a family of types over an instance of a declared type: Π (z : S(as)). U(l)."],
  ["K114", "The eliminator has a clause for every constructor; close it."],
  ["K115", "The clause's type is not the constructor's clause type: its boundaries must be the displayed boundaries of 3.6."],
  ["K116", "The eliminator lacks a clause: every constructor, the squash included, needs one."],
  ["K117", "HIT join allocation failed."],
  ["K118", "HIT reversal allocation failed."],
  ["K119", "HIT endpoint allocation failed."],
  ["K120", "HIT substitution interval allocation failed."],
  ["K121", "Missing HIT transport face."],
  ["K122", "HIT elimination filling allocation failed."],
  ["K123", "Interval constant allocation failed."],
  ["K124", "A constructor's type has fewer arguments than its application."],
  ["K125", "A constructor's dimensions are its result type's path layers."],
  ["K126", "Transport filling allocation failed."],
  ["K127", "Unchecked homogeneous composition face."],
  ["K128", "Transport computation requires a declared higher sort."],
  ["K129", "Signature table exhausted."],
  ["K130", "Signature table allocation failed."],
  ["K131", "A signature has too many constructors."],
  ["K132", "Constructor table allocation failed."],
  ["K133", "A binder in a boundary reuses a name of the signature."],
  ["K134", "A binder's type in a boundary mentions the sort, a constructor or a position (section 1.4)."],
  ["K135", "A path abstraction or application in a boundary carries a type that is not a cube over the sort (section 1.4)."],
  ["K136", "A boundary may not contain a composition, hcomp or transport (section 1.4, Q3)."],
  ["K137", "A boundary applies a position to exactly its arity (section 1.4)."],
  ["K138", "A boundary applies an earlier constructor to all its data and positions (section 1.4)."],
  ["K139", "A constructor's boundary names the constructor itself (section 1.5)."],
  ["K140", "A boundary must be a constructor expression: a position or an earlier constructor, applied, or a path application or abstraction of one (section 1.4)."],
  ["K141", "A constructor has too many dimensions, or a position too deep a cube."],
  ["K142", "A position's type and a constructor's result end in the sort, or in an iterated path type over it (section 1.2)."],
  ["K143", "A constructor's argument reuses a name of the signature."],
  ["K144", "A constructor has too many arguments."],
  ["K145", "A position's arity reuses a name of the signature."],
  ["K146", "A position's arity mentions the sort, a constructor or a position: the sort occurs only at the end of a position (section 1.3)."],
  ["K147", "A position's arity is too long."],
  ["K148", "A data argument follows a position; the kernel requires all data first (section 1.2)."],
  ["K149", "Expected a signature judgement."],
  ["K150", "The signature judgement names no signature."],
  ["K151", "The signature is already admitted; an admitted signature never changes."],
  ["K152", "Only the signature's latest judgement continues it."],
  ["K153", "Declared types (H1) are switched off in this kernel; CC_EXTENSION_H1 switches them on."],
  ["K154", "A signature's former type must be closed."],
  ["K155", "A truncation level is at most the kernel's bound."],
  ["K156", "A signature needs a sort symbol."],
  ["K157", "A signature has too many universe parameters."],
  ["K158", "A signature's universe parameters range below UU0: x < ω."],
  ["K159", "A signature's former type is Π (xs < ω). Π (ps : Ps). U(ℓ)."],
  ["K160", "A signature's parameters need distinct symbols, other than the sort's."],
  ["K161", "The classification marks a universe parameter the signature does not have."],
  ["K162", "An erased universe parameter needs a determining occurrence: a parameter whose type ends in U(x) (section 1.1). Otherwise it is recorded."],
  ["K163", "Signature allocation failed."],
  ["K164", "A constructor type's context holds a dimension entry."],
  ["K165", "A constructor's type names the constructor itself (section 1.5)."],
  ["K166", "The sort entry's type is not the signature's universe."],
  ["K167", "A parameter entry's type is not the signature's."],
  ["K168", "A constructor entry's type is not that constructor's."],
  ["K169", "A constructor type's context holds an entry that is not the signature's: a later constructor, or a name from outside the signature (section 1.5)."],
  ["K170", "A constructor type is derived in the signature's universe U(ℓ); lift it there first."],
  ["K171", "A constructor needs a symbol."],
  ["K172", "A constructor's symbol must be new to the signature."],
  ["K173", "A constructor type mentions an erased universe parameter; only a recorded one may occur there (section 1.1)."],
  ["K174", "Expected an instance of a declared type."],
  ["K175", "Only an admitted signature has instances."],
  ["K176", "A parameter's type does not end in a universe where the signature's does."],
  ["K177", "An erased universe parameter has no determining occurrence."],
  ["K178", "Expected an instance in progress."],
  ["K179", "An instance takes its recorded levels first, one for each recorded universe parameter."],
  ["K180", "An instance takes its recorded levels before its parameters."],
  ["K181", "The instance already has all its parameters."],
  ["K182", "The instance's parameters and levels are not the signature's."],
  // Kernel: instructions
  ["K201", "An equality has sides 0 and 1."],
  ["K202", "The type is not included in the target type."],
  ["K203", "Interval allocation failed."],
  ["K204", "Eta needs a term of a Π, level Π, Σ, path or Glue type."],
  ["K205", "Missing position."],
  ["K206", "The position leaves the term."],
  ["K207", "Position depth exceeded."],
  ["K208", "Beta needs a lambda applied to an argument, or a level lambda to a level."],
  ["K209", "Delta needs a definition."],
  ["K210", "Iota needs an eliminator or projection applied to a constructor."],
  ["K211", "A path step needs a path application."],
  ["K212", "Interval copy failed."],
  ["K213", "A path step needs a path lambda, or an endpoint of the annotated type."],
  ["K214", "A face step needs a composition with a tube on a face that holds."],
  ["K215", "A Glue step needs glue [φ ↦ t] (unglue b) whose two Glue types agree, and whose t is b on φ, after normalization."],
  ["K216", "Unknown step rule."],
  ["K217", "A composition system is closed by Comp before it is rewritten."],
  ["K218", "An open signature or an instance in progress is continued by its own instructions, not rewritten."],
  ["K219", "A judgement has sides 0 (term), 2 (type), and 1 for an equality's other term."],
  ["K220", "Replacement allocation failed."],
  ["K221", "A path application's annotation is replaced only by a path type."],
  ["K222", "Replacing a subterm that uses a composition's dimension is not supported."],
  ["K223", "The replacing equality lacks an entry for a bound name it uses."],
  ["K224", "One entry would be bound twice on the path."],
  ["K225", "The last piece must first be shown to agree with the pieces it overlaps."],
  ["K226", "A piece may overlap only the first 64 pieces."],
  ["K227", "A Glue piece's face is one conjunction of endpoint equations, or 0."],
  ["K228", "A Glue piece's face must be consistent."],
  ["K229", "A Glue piece must already be restricted to its face."],
  ["K230", "That piece's face is not one clause."],
  ["K231", "The Glue type has no piece at that position."],
  ["K232", "Not a Glue type under construction."],
  ["K233", "The last piece does not overlap that piece, or already agrees with it."],
  ["K234", "A Glue term needs a Glue type."],
  ["K235", "The Glue term has a value for every piece of its type."],
  ["K236", "A Glue term's value must already be restricted to its face."],
  ["K237", "A value on the face 0 takes no equality."],
  ["K238", "Only an element of a Glue type is unglued."],
  ["K239", "Only a term of a path type can be applied to a dimension."],
  ["K240", "A path applies at a dimension, 0 or 1."],
  ["K241", "An endpoint is 0 or 1."],
  ["K242", "Only a term of a path type can be applied to an interval formula."],
  ["K243", "A path applies at an interval formula."],
  ["K244", "The base of a composition may not use its dimension."],
  ["K245", "That tube's face is not one clause."],
  ["K246", "The system has no tube at that position."],
  ["K247", "The last tube must first be shown to agree with the tubes it overlaps."],
  ["K248", "Not a composition system."],
  ["K249", "A tube's face is one conjunction of endpoint equations, or 0."],
  ["K250", "A tube on the face 0 takes no equality."],
  ["K251", "A tube's face must be consistent."],
  ["K252", "A tube's face may not use the composition's dimension."],
  ["K253", "A tube must already be restricted to its face."],
  ["K254", "A tube may overlap only the first 64 tubes of a system."],
  ["K255", "Not a system of tubes."],
  ["K256", "The last tube does not overlap that tube, or already agrees with it."],
  ["K257", "A declared data sort has no formal composition or transport: compose it with Comp, whose tube φ ↦ u_0 transports (Q1)."],
  ["K258", "A homogeneous composition's type may not use its dimension."],
  ["K259", "A transport's face is a face formula."],
  ["K260", "A transport's tubes are its face's clauses, in order."],
  ["K261", "Instruction store handle space exhausted."],
  ["K262", "Instruction store allocation overflow."],
  ["K263", "Instruction store allocation failed."],
  ["K264", "Unknown context entry."],
  ["K265", "A universe variable is not a term: use it in a level, as U(x)."],
  ["K266", "Expected a type: a term of a universe."],
  ["K267", "Two dimension entries with one index meet in a context."],
  ["K268", "A context entry still depends on the discharged entry."],
  ["K269", "The binder would capture another dimension entry with its index."],
  ["K270", "Entry index allocation failed."],
  ["K271", "A context entry needs a symbol."],
  ["K272", "The symbol already names a context entry."],
  ["K273", "Expected a level entry."],
  ["K274", "Dimension outside the native range."],
  ["K275", "Unbound level variable."],
  ["K276", "A term variable is not a level."],
  ["K277", "A universe level exceeds the kernel's bound."],
  ["K278", "A motive is a family of types: Π(x : A). U(l)."],
  ["K279", "An injection needs a sum type."],
  ["K280", "Sum induction needs a value of a sum type."],
  ["K281", "Only a term of a Π type can be applied."],
  ["K282", "Only a term of a level Π can be instantiated at a level."],
  ["K283", "Instantiation needs a finite level, below ω."],
  ["K284", "A pair needs a Σ type."],
  ["K285", "Only a term of a Σ type has projections."],
  ["K286", "Only a Π or Σ type has a domain."],
  ["K287", "Only a Π or Σ type has a family."],
  ["K288", "Only a closed judgement can be defined."],
  ["K289", "Definition symbol is already registered."],
  ["K290", "Unknown checked definition reference."],
  ["K291", "A declared type's instance reads finite levels only, below ω (Q16)."],
  ["K292", "A restriction's face is one consistent conjunction of endpoint equations."],
  ["K293", "A face entry is an assumption, not a variable or a dimension."],
  ["K294", "A split step needs a composition with a tube on a face of several clauses, or on the face 0."],
  // Kernel: terms and computation
  ["K301", "A signature is still open; close it before committing."],
  ["K302", "Checkpoint compaction allocation failed."],
  ["K303", "Unchecked composition face reached reduction."],
  ["K304", "Composition filling formula allocation failed."],
  ["K305", "Filling direction allocation failed."],
  ["K306", "Backward filling direction allocation failed."],
  ["K307", "Path composition direction allocation failed."],
  ["K308", "Singleton contraction interval allocation failed."],
  ["K309", "Glue endpoint face allocation failed."],
  ["K310", "Preservation interval allocation failed."],
  ["K311", "Glue universal face allocation failed."],
  ["K312", "Glue boundary face allocation failed."],
  ["K313", "Glue composition allocation overflow."],
  ["K314", "Glue composition allocation failed."],
  ["K315", "Universe composition interval allocation failed."],
  ["K316", "Level normal form too large."],
  ["K317", "Level normal form allocation failed."],
  ["K318", "Expected a level."],
  ["K319", "A level successor counts at least one."],
  ["K320", "A bound is not a level."],
  ["K321", "A level variable's key is not a symbol."],
  ["K322", "Level normalization depth exceeded."],
  ["K323", "Composition face allocation failed."],
  ["K324", "Syntax memo allocation failed."],
  ["K325", "Alpha-comparison scope counter exhausted."],
  ["K326", "Native conversion recursion depth exceeded."],
  ["K327", "Alpha-comparison memo allocation failed."],
  ["K328", "An endpoint substitution needs a dimension and 0 or 1."],
  ["K329", "Unchecked partial face reached reduction."],
  ["K330", "Unknown definition reached reduction."],
  ["K331", "Unchecked Glue face reached reduction."],
  ["K332", "Glue eta face allocation failed."],
  ["K333", "Unchecked Glue projection reached reduction."],
  ["K334", "Path application requires an interval expression."],
  ["K335", "Unchecked path application reached reduction."],
  ["K336", "Native reduction recursion depth exceeded."],
  ["K337", "Native normal-form depth exceeded."],
  ["K338", "Kernel checking/reduction budget exhausted."],
  ["K339", "Unknown term constructor."],
  ["K340", "A universe's level is its child; its payload must be zero."],
  ["K341", "Missing syntax child."],
  ["K342", "Invalid syntax child handle."],
  ["K343", "A formula handle names no registered formula."],
  ["K344", "Native prototype syntax depth exceeds 512."],
  ["K345", "Term handle space exhausted."],
  ["K346", "Term arena capacity overflow."],
  ["K347", "Term arena allocation failed."],
  ["K348", "Normal cache allocation failed."],
  ["K349", "Term symbol space exhausted."],
  ["K350", "Formula handle space exhausted."],
  ["K351", "Formula arena capacity overflow."],
  ["K352", "Formula arena allocation failed."],
  ["K353", "Formula copy failed."],
  ["K354", "Fresh symbol space exhausted."],
  ["K355", "Native prototype has exhausted its 64 dimension names."],
  ["K356", "Term substitution dimension allocation failed."],
  ["K357", "Malformed composition tube list."],
  ["K358", "Invalid dimension substitution."],
  ["K359", "Dimension binder outside native range."],
  ["K360", "Fresh dimension allocation failed."],
  ["K361", "Endpoint allocation failed."],
  ["K362", "Invalid interval variable."],
  ["K363", "Invalid face variable."],
  ["K364", "Face copy failed."],
  // Warnings
  ["W701", "None of … is used after this obtain: remove it."],
  ["W702", "… is never used after this let: remove it."],
  ["W703", "… is unused: the return type does not mention it and the successor clause does not use it. Omit as …: induction … return …."],
  ["W704", "… is unused: the return type does not mention it. Omit as …: match … return …."],
  ["W705", "… is unused in the body: write … instead of … … : …. …."],
  ["W706", "… is unused in the body: take it out of the group and write … for it."],
  ["W707", "… is unused: the return type does not mention it. Omit as …: induction … return …."],
];

// A message's pattern: its text, where … matches any text, from the start
// of the reported message.
const patterns = diagnostics.filter(([, , status]) => status !== "retired").map(([code, message]) => ({
  code, literal: message.replace(/…/g, "").length,
  pattern: new RegExp(`^${message.split("…").map(part => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("[\\s\\S]*?")}`),
}));

// A reported message with its code in front, as the REPL and the workspace
// show it: "E301: Type mismatch: …". A message without a code is shown as it is.
export function withCode(message, code = diagnosticCode(message)) {
  return code ? `${code}: ${message}` : message;
}

// One line for a diagnostic, as the command-line checker prints it:
// "error E301 at line 2:3 (name): message". A position at the end of the
// message, " at 2:3", moves to the front.
export function diagnosticLine({ severity = "error", code, message, line, column, declaration }) {
  const at = / at (\d+):(\d+)$/.exec(message);
  if (at && line === undefined) [line, column, message] = [at[1], at[2], message.slice(0, at.index)];
  return `${severity}${code ? ` ${code}` : ""}${line !== undefined ? ` at line ${line}:${column}` : ""}`
    + `${declaration ? ` (${declaration})` : ""}: ${message}`;
}

// The code of a reported message, or null: of the patterns that match it,
// the one with the most text of its own, so the most specific.
export function diagnosticCode(message) {
  let best = null;
  for (const entry of patterns) if (entry.pattern.test(message) && (!best || entry.literal > best.literal)) best = entry;
  return best?.code ?? null;
}
