import catalogue from "./proofs/catalogue.mjs";

// Every proof has one browsing topic; mathematical dependencies can cross topics.
export const proofTopics = [
  { id: "basic-logic", title: "Basic Logic" },
  { id: "sets-maps", title: "Sets & Maps" },
  { id: "arithmetic", title: "Arithmetic & Number Theory" },
  { id: "finite-counting", title: "Finite Types & Counting" },
  { id: "algebra", title: "Algebra" },
  { id: "homotopy", title: "Homotopy" },
  { id: "topology", title: "Topology & Winding" },
  { id: "general-analysis", title: "General Analysis" },
  { id: "real-analysis", title: "Real Analysis" },
  { id: "complex-analysis", title: "Complex Analysis" },
  { id: "curves-sampling", title: "Curves & Sampling" },
  { id: "contour-integration", title: "Contour Integration" },
  { id: "kernel-audits", title: "Kernel Audits" },
];

export const proofChoices = [
  { id: "affine_integral_linearity", topic: "contour-integration", title: "Curve integrals · complex linearity and equality along the curve", complexDevelopment: true },
  { id: "curve_integrand_sums", topic: "contour-integration", title: "Curve contours · linearity in the sampled integrand", complexDevelopment: true },
  { id: "field_uniform_radii", topic: "general-analysis", title: "Uniform continuity · constructive common positive radii", complexDevelopment: true },
  { id: "complex_uniform_operations", topic: "complex-analysis", title: "Complex continuity · addition with an explicit modulus", complexDevelopment: true },
  { id: "complex_scalar_continuity", topic: "complex-analysis", title: "Complex continuity · fixed scalar multiplication and limits", complexDevelopment: true },
  { id: "affine_integrals", topic: "contour-integration", title: "Curve integrals · construct the affine dyadic limit", complexDevelopment: true },
  { id: "affine_integral_midpoint", topic: "contour-integration", title: "Curve integrals · splitting at the midpoint", complexDevelopment: true },
  { id: "affine_integral_constants", topic: "contour-integration", title: "Curve integrals · integrating a constant", complexDevelopment: true },
  { id: "affine_dyadic_limits", topic: "contour-integration", title: "Curve integrals · actual dyadic sums are Cauchy", complexDevelopment: true },
  { id: "complex_refinement_cauchy", topic: "complex-analysis", title: "Complex limits · common refinements give a Cauchy modulus", complexDevelopment: true },
  { id: "curve_sample_sums", topic: "contour-integration", title: "Curve contours · concatenating the actual mapped sums", complexDevelopment: true },
  { id: "group_univalence", topic: "algebra", title: "Groups · isomorphism is equality" },
  { id: "circle_group_identity", topic: "homotopy", title: "Circle · the loop group equals the integer group" },
  { id: "group_identity", topic: "algebra", title: "Groups · bundled structures and identity paths" },
  { id: "group_isomorphisms", topic: "algebra", title: "Groups · extensionality of isomorphisms" },
  { id: "group_total_identity", topic: "algebra", title: "Groups · the contractible isomorphism family" },
  { id: "identity_systems", topic: "homotopy", title: "Identity systems · canonical path equivalences" },
  { id: "subdivision_tagged_zip", topic: "curves-sampling", title: "Curve sampling · combine coarse and refined tag conditions", complexDevelopment: true },
  { id: "dyadic_refinement_mesh", topic: "curves-sampling", title: "Curve sampling · dyadic refinement below a requested mesh", complexDevelopment: true },
  { id: "curve_refinement_estimates", topic: "contour-integration", title: "Curve contours · estimates for specified fine samples", complexDevelopment: true },
  { id: "dyadic_contour_estimates", topic: "contour-integration", title: "Curve contours · uniform errors between dyadic levels", complexDevelopment: true },
  { id: "interval_midpoint_data", topic: "curves-sampling", title: "Curve sampling · a midpoint and its checked bounds", complexDevelopment: true },
  { id: "dyadic_data", topic: "curves-sampling", title: "Curve sampling · exact dyadic construction equations", complexDevelopment: true },
  { id: "dyadic_refinement", topic: "curves-sampling", title: "Curve sampling · later dyadic levels refine earlier ones", complexDevelopment: true },
  { id: "subdivision_transport", topic: "curves-sampling", title: "Curve sampling · transport refinement endpoints", complexDevelopment: true },
  { id: "subdivision_join", topic: "curves-sampling", title: "Curve sampling · join per-edge refinement families", complexDevelopment: true },
  { id: "subdivision_join_conditions", topic: "curves-sampling", title: "Curve sampling · preserve refinement conditions under joins", complexDevelopment: true },
  { id: "subdivision_refinement", topic: "curves-sampling", title: "Curve sampling · compose refinement sum certificates", complexDevelopment: true },

  { id: "fine_interval_tails", topic: "curves-sampling", title: "Curve sampling · fine samples at every sufficiently deep level", complexDevelopment: true },
  { id: "dyadic_convergence", topic: "curves-sampling", title: "Curve sampling · explicit bounds and dyadic convergence", complexDevelopment: true },
  { id: "dyadic_tails", topic: "curves-sampling", title: "Curve sampling · monotone widths and eventual mesh bounds", complexDevelopment: true },
  { id: "fine_interval_samples", topic: "curves-sampling", title: "Curve sampling · arbitrarily fine constructive subdivisions", complexDevelopment: true },
  { id: "dyadic_decay", topic: "curves-sampling", title: "Curve sampling · Archimedean decay of dyadic widths", complexDevelopment: true },
  { id: "dyadic_width_bounds", topic: "curves-sampling", title: "Curve sampling · scalar bounds for repeated halving", complexDevelopment: true },
  { id: "dyadic_mesh", topic: "curves-sampling", title: "Curve sampling · dyadic bounds imply strict mesh bounds", complexDevelopment: true },
  { id: "dyadic_sampling", topic: "curves-sampling", title: "Curve sampling · repeated bisection with exact edge counts", complexDevelopment: true },
  { id: "sample_condition_maps", topic: "curves-sampling", title: "Curve sampling · map local tag conditions", complexDevelopment: true },
  { id: "sample_join_conditions", topic: "curves-sampling", title: "Curve sampling · concatenation preserves admissible tags", complexDevelopment: true },
  { id: "interval_bisection", topic: "curves-sampling", title: "Curve sampling · constructive midpoint subdivisions", complexDevelopment: true },
  { id: "affine_partition_refinement", topic: "contour-integration", title: "Curve contours · uniform refinement across an entire partition", complexDevelopment: true },
  { id: "interval_subdivisions", topic: "curves-sampling", title: "Curve sampling · subdivision admissibility and total error radius", complexDevelopment: true },
  { id: "complex_subdivision_estimates", topic: "contour-integration", title: "Curve contours · sum subdivision errors across a partition", complexDevelopment: true },
  { id: "complex_perturbations", topic: "complex-analysis", title: "Complex estimates · explicit additive error certificates", complexDevelopment: true },
  { id: "sample_subdivision_conditions", topic: "curves-sampling", title: "Curve sampling · conditions on each tagged subdivision", complexDevelopment: true },
  { id: "sample_subdivisions", topic: "curves-sampling", title: "Curve sampling · flatten subdivisions across a partition", complexDevelopment: true },
  { id: "affine_refinement", topic: "contour-integration", title: "Curve contours · width-scaled finite refinement errors", complexDevelopment: true },
  { id: "interval_refinement", topic: "curves-sampling", title: "Curve sampling · refinement tags in a common interval", complexDevelopment: true },
  { id: "parameter_refinement", topic: "contour-integration", title: "Curve contours · coarse edge and refined sum identity", complexDevelopment: true },
  { id: "sample_refinement_tags", topic: "curves-sampling", title: "Curve sampling · repeated tags and endpoint containment", complexDevelopment: true },
  { id: "curve_tag_stability", topic: "contour-integration", title: "Curve contours · fine meshes control admissible tag changes", complexDevelopment: true },
  { id: "uniform_curve_tags", topic: "curves-sampling", title: "Curve sampling · continuity bounds integrand errors", complexDevelopment: true },
  { id: "interval_sampling", topic: "curves-sampling", title: "Curve sampling · admissible endpoint tags and mesh bounds", complexDevelopment: true },
  { id: "interval_tag_bounds", topic: "curves-sampling", title: "Curve sampling · tags in a short interval are close", complexDevelopment: true },
  { id: "sample_tagged", topic: "curves-sampling", title: "Curve sampling · explicit endpoint tag lists", complexDevelopment: true },
  { id: "parameter_tag_sampling", topic: "curves-sampling", title: "Curve sampling · local tag bounds control all samples", complexDevelopment: true },
  { id: "curve_contour_estimates", topic: "contour-integration", title: "Curve contours · finite tag-change estimates", complexDevelopment: true },
  { id: "parameter_contour_estimates", topic: "contour-integration", title: "Curve contours · finite estimates with parameter weights", complexDevelopment: true },
  { id: "curve_contour_limits", topic: "contour-integration", title: "Curve contours · affine tag-independent limits", complexDevelopment: true },
  { id: "parameter_contour_limits", topic: "contour-integration", title: "Curve contours · limits with parameter weights", complexDevelopment: true },
  { id: "parameter_contour_bounds", topic: "contour-integration", title: "Curve contours · parameter-based error estimates", complexDevelopment: true },
  { id: "parameter_increment_bounds", topic: "contour-integration", title: "Curve contours · coordinate increment certificates", complexDevelopment: true },
  { id: "parameter_contours", topic: "contour-integration", title: "Curve contours · sums on mapped samples", complexDevelopment: true },
  { id: "sample_maps", topic: "curves-sampling", title: "Curve sampling · mapping vertices and tags", complexDevelopment: true },
  { id: "complex_curve_variation", topic: "curves-sampling", title: "Complex curves · bounded coordinate variation", complexDevelopment: true },
  { id: "affine_variation", topic: "curves-sampling", title: "Curve sampling · ordered affine increment bounds", complexDevelopment: true },
  { id: "interval_weights", topic: "curves-sampling", title: "Curve sampling · telescoping interval weights", complexDevelopment: true },
  { id: "sample_relations", topic: "curves-sampling", title: "Curve sampling · conditions on adjacent vertices", complexDevelopment: true },
  { id: "complex_curves", topic: "curves-sampling", title: "Complex curves · continuous straight segments and endpoints", complexDevelopment: true },
  { id: "complex_affine", topic: "curves-sampling", title: "Complex curves · constructive uniform continuity", complexDevelopment: true },
  { id: "field_interval", topic: "real-analysis", title: "Curve parameters · the closed unit interval", complexDevelopment: true },
  { id: "field_affine", topic: "real-analysis", title: "Affine estimates · parameter differences control increments", complexDevelopment: true },
  { id: "complex_contour_tag_limits", topic: "contour-integration", title: "Complex contours · tag-independent limits", complexDevelopment: true },
  { id: "complex_contour_bounds", topic: "contour-integration", title: "Complex contours · coordinate variation estimates", complexDevelopment: true },
  { id: "field_scale_limits", topic: "general-analysis", title: "Limits · fixed factors preserve vanishing errors", complexDevelopment: true },
  { id: "complex_convergence", topic: "complex-analysis", title: "Complex limits · convergence and Cauchy definitions", complexDevelopment: true },
  { id: "complex_contour_samples", topic: "contour-integration", title: "Complex contours · finite sums", complexDevelopment: true },
  { id: "contour_tag_limits", topic: "contour-integration", title: "Contour estimates · vanishing tag errors", complexDevelopment: true },
  { id: "contour_error_bounds", topic: "contour-integration", title: "Contour estimates · error times variation", complexDevelopment: true },
  { id: "complex_magnitude", topic: "complex-analysis", title: "Complex estimates · coordinate bounds without square roots", complexDevelopment: true },
  { id: "field_magnitude_close", topic: "general-analysis", title: "Error bounds · closeness and convergence to zero", complexDevelopment: true },
  { id: "sample_magnitude_bounds", topic: "general-analysis", title: "Finite estimates · weighted sums and variation", complexDevelopment: true },
  { id: "sample_magnitude", topic: "general-analysis", title: "Finite estimates · bounds at sampled edges", complexDevelopment: true },
  { id: "field_magnitude", topic: "real-analysis", title: "Ordered estimates · constructive magnitude bounds", complexDevelopment: true },
  { id: "complex_contour_sums", topic: "contour-integration", title: "Contour sums · complex composition and backtracking", complexDevelopment: true },
  { id: "contour_examples", topic: "contour-integration", title: "Contour sums · finite backtracking errors", complexDevelopment: true },
  { id: "contour_refinement", topic: "contour-integration", title: "Contour sums · refinement and tag errors", complexDevelopment: true },
  { id: "contour_samples", topic: "contour-integration", title: "Contour sums · samples and oriented increments", complexDevelopment: true },
  { id: "contour_sums", topic: "contour-integration", title: "Contour sums · linearity and telescoping", complexDevelopment: true },
  { id: "sample_error_bounds", topic: "general-analysis", title: "Finite sums · accumulated error bounds", complexDevelopment: true },
  { id: "sample_sum_laws", topic: "general-analysis", title: "Finite sums · composition and telescoping", complexDevelopment: true },
  { id: "sample_chains", topic: "curves-sampling", title: "Sampling data · vertices, tags and concatenation", complexDevelopment: true },
  { id: "homotopy_limits", topic: "general-analysis", title: "Homotopy periods · limits descend from curves", punctureDevelopment: true },
  { id: "surjective_descent", topic: "sets-maps", title: "Descent · unique values without chosen representatives" },
  { id: "descent_loop_laws", topic: "general-analysis", title: "Homotopy periods · composition through representatives", punctureDevelopment: true },
  { id: "complex_limit_periods", topic: "general-analysis", title: "Complex periods · constructed from Cauchy approximations", punctureDevelopment: true },
  { id: "limit_periods", topic: "general-analysis", title: "Homotopy periods · limits of approximate laws", punctureDevelopment: true },
  { id: "complex_limits", topic: "complex-analysis", title: "Complex analysis · completeness and limit laws", complexDevelopment: true },
  { id: "field_asymptotics", topic: "general-analysis", title: "Limits · vanishing errors preserve the limit", complexDevelopment: true },
  { id: "field_limits", topic: "general-analysis", title: "Limits · uniqueness, addition and Cauchy sequences", complexDevelopment: true },
  { id: "field_closeness", topic: "general-analysis", title: "Error bounds · triangle, addition and separation", complexDevelopment: true },
  { id: "ordered_halves", topic: "real-analysis", title: "Ordered fields · constructive halving", complexDevelopment: true },
  { id: "cauchy_ordered", topic: "real-analysis", title: "Cauchy quotient · closeness assumptions proved", realDevelopment: true },
  { id: "complex_numbers", topic: "complex-analysis", title: "Complex numbers · coordinates and operations", complexDevelopment: true },
  { id: "puncture_periods", topic: "topology", title: "Puncture periods · the winding sum formula", punctureDevelopment: true },
  { id: "complex_periods", topic: "topology", title: "Complex periods · local contributions and winding", punctureDevelopment: true },
  { id: "puncture_period_examples", topic: "topology", title: "Periods · noncontractible loop with zero period", punctureDevelopment: true },
  { id: "integer_multiples", topic: "algebra", title: "Additive groups · signed integer multiples" },
  { id: "finite_sums", topic: "algebra", title: "Finite sums · additivity and single terms" },
  { id: "ordered_bounds", topic: "real-analysis", title: "Ordered fields · constructive inequality bounds", complexDevelopment: true },
  { id: "quadratic_identities", topic: "algebra", title: "Quadratic algebra · parallelogram identity", complexDevelopment: true },
  { id: "circle_degree", topic: "topology", title: "Circle degree · obstruction to contraction", complexDevelopment: true },
  { id: "complex_deformation", topic: "complex-analysis", title: "Complex deformations · dominant term avoids zero", complexDevelopment: true },
  { id: "homotopy_paths", topic: "homotopy", title: "Homotopies · moving basepoints and contractions", complexDevelopment: true },
  { id: "complex_inverses", topic: "complex-analysis", title: "Complex numbers · constructive inverses and apartness", complexDevelopment: true },
  { id: "classical_complex_inverses", topic: "complex-analysis", title: "Complex numbers · nonzero inverses using excluded middle", complexDevelopment: true },
  { id: "ordered_squares", topic: "real-analysis", title: "Ordered fields · constructive square positivity", complexDevelopment: true },
  { id: "complex_norm_coordinates", topic: "complex-analysis", title: "Complex numbers · multiplicative norm", complexDevelopment: true },
  { id: "complex_algebra", topic: "complex-analysis", title: "Complex numbers · ring, conjugation and inverses", complexDevelopment: true },
  { id: "complex_polynomials", topic: "complex-analysis", title: "Polynomials · roots and algebraic closure target", complexDevelopment: true },
  { id: "polynomial_difference", topic: "algebra", title: "Polynomials · difference and factor identities", complexDevelopment: true },
  { id: "complex_coordinates", topic: "complex-analysis", title: "Complex numbers · coordinate identities", complexDevelopment: true },
  { id: "ring_laws", topic: "algebra", title: "Ring algebra · derived identities", complexDevelopment: true },
  { id: "field_products", topic: "real-analysis", title: "Field foundations · products are sets", complexDevelopment: true },
  { id: "bouquet_generation", topic: "homotopy", title: "Punctures · every loop is a word", punctureDevelopment: true },
  { id: "puncture_noncommutative", topic: "topology", title: "Punctures · zero winding, nontrivial loop", punctureDevelopment: true },
  { id: "bouquet_invariants", topic: "homotopy", title: "Loop invariants · determined by generators", punctureDevelopment: true },
  { id: "puncture_winding", topic: "topology", title: "Punctures · winding around each generator", punctureDevelopment: true },
  { id: "puncture_graph", topic: "topology", title: "Punctures · graph and generating loops", punctureDevelopment: true },
  { id: "loop_words", topic: "homotopy", title: "Loop words · evaluation and cancellation", punctureDevelopment: true },
  { id: "bouquet_actions", topic: "homotopy", title: "Loop actions · transport in local systems", punctureDevelopment: true },
  { id: "bouquet_cover", topic: "homotopy", title: "Loop generation · auxiliary family", punctureDevelopment: true },
  { id: "path_actions", topic: "homotopy", title: "Paths · append, map and reconnect", punctureDevelopment: true },
  { id: "complete_fields", topic: "real-analysis", title: "Real numbers · shared completeness interface", realDevelopment: true },
  { id: "dedekind_cuts", topic: "real-analysis", title: "Real numbers · constructive Dedekind cuts", realDevelopment: true },
  { id: "boolean_cuts", topic: "real-analysis", title: "Real numbers · classical Boolean cuts", realDevelopment: true },
  { id: "cauchy_quotient", topic: "real-analysis", title: "Real numbers · ordinary Cauchy quotient", realDevelopment: true },
  { id: "ordered_fields", topic: "real-analysis", title: "Ordered fields · laws and algebraic lemmas", realDevelopment: true },
  { id: "set_quotients", topic: "sets-maps", title: "Equivalence classes · representatives and choice", realDevelopment: true },
  { id: "field_logic", topic: "basic-logic", title: "Logic in U1 · propositions and truncation", realDevelopment: true },
  { id: "field_extensionality", topic: "real-analysis", title: "Field foundations · predicate equality", realDevelopment: true },
  { id: "surjections", topic: "sets-maps", title: "Surjections · right inverses and choice" },
  { id: "maps", topic: "sets-maps", title: "Maps · injections, embeddings and fibers" },
  { id: "classical", topic: "basic-logic", title: "Classical logic · excluded middle" },
  { id: "schroeder_bernstein", topic: "sets-maps", title: "Cantor–Schröder–Bernstein · mutual injections" },
  { id: "binomial_counting", topic: "finite-counting", title: "Binomial types · finite cardinality" },
  { id: "permutations", topic: "finite-counting", title: "Permutations · factorials" },
  { id: "binomial_types", topic: "finite-counting", title: "Binomial types · Rijke construction" },
  { id: "binomial_pascal", topic: "finite-counting", title: "Binomial types · Pascal bijection" },
  { id: "truncation", topic: "basic-logic", title: "Propositional truncation · explicit principles" },
  { id: "finite_cancellation", topic: "finite-counting", title: "Finite types · cancellation and cardinality" },
  { id: "bijection_equality", topic: "sets-maps", title: "Bijections · equality and coherence" },
  { id: "function_counting", topic: "finite-counting", title: "Finite functions · powers" },
  { id: "binomial", topic: "finite-counting", title: "Subsets · Pascal counting" },
  { id: "finite", topic: "finite-counting", title: "Finite types · sums of Unit" },
  { id: "equivalences", topic: "sets-maps", title: "Bijections · reusable constructions" },
  { id: "groups", topic: "algebra", title: "Groups · structures and isomorphisms" },
  { id: "sets", topic: "sets-maps", title: "Sets · decidable equality" },
  { id: "circle", topic: "homotopy", title: "Circle · fundamental group is Z" },
  { id: "integers", topic: "arithmetic", title: "Integers · successor equivalence" },
  { id: "paths", topic: "homotopy", title: "Paths · equality reasoning" },
  { id: "suspension", topic: "homotopy", title: "Suspension & the circle · foundations" },
  { id: "euclid", topic: "arithmetic", title: "Euclid · mathematical proof" },
  { id: "basics", topic: "basic-logic", title: "Functions, pairs & induction · examples" },
  { id: "primes", topic: "arithmetic", title: "Primes · mathematical foundations" },
  ...catalogue.map((p) => ({
    ...p,
    id: p.id + "_construction",
    topic: "kernel-audits",
    file: p.id + ".construction.proof",
    title: p.title + " · kernel audit",
  })),
];

export function proofsInTopic(topic) {
  return proofChoices.filter(proof => proof.topic === topic)
    .sort((left, right) => left.title.localeCompare(right.title));
}
